// This file is auto-generated by @hey-api/openapi-ts

export const Body_exams_upload_exam_fileSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        },
        document_type: {
            '$ref': '#/components/schemas/ExamDocumentType',
            default: 'blank_exam'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_exams-upload_exam_file'
} as const;

export const Body_exams_upload_student_submissionSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        },
        student_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Student Name'
        },
        student_identifier: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Student Identifier'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_exams-upload_student_submission'
} as const;

export const Body_files_upload_fileSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_files-upload_file'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ExamCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        subject: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subject'
        },
        grade_level: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade Level'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ExamCreate'
} as const;

export const ExamDocumentPublicSchema = {
    properties: {
        document_type: {
            '$ref': '#/components/schemas/ExamDocumentType',
            default: 'blank_exam'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        exam_id: {
            type: 'string',
            format: 'uuid',
            title: 'Exam Id'
        },
        stored_file_id: {
            type: 'string',
            format: 'uuid',
            title: 'Stored File Id'
        },
        stored_file: {
            '$ref': '#/components/schemas/StoredFilePublic'
        },
        page_count: {
            type: 'integer',
            title: 'Page Count',
            default: 1
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'exam_id', 'stored_file_id', 'stored_file'],
    title: 'ExamDocumentPublic'
} as const;

export const ExamDocumentTypeSchema = {
    type: 'string',
    enum: ['blank_exam', 'answer_key'],
    title: 'ExamDocumentType'
} as const;

export const ExamDocumentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ExamDocumentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ExamDocumentsPublic'
} as const;

export const ExamPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        subject: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subject'
        },
        grade_level: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade Level'
        },
        status: {
            '$ref': '#/components/schemas/ExamStatus',
            default: 'draft'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ExamPublic'
} as const;

export const ExamRegionCreateSchema = {
    properties: {
        label: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Label'
        },
        region_type: {
            '$ref': '#/components/schemas/ExamRegionType',
            default: 'question'
        },
        page_number: {
            type: 'integer',
            minimum: 1,
            title: 'Page Number',
            default: 1
        },
        x: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'X'
        },
        y: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Y'
        },
        width: {
            type: 'number',
            maximum: 1,
            exclusiveMinimum: 0,
            title: 'Width'
        },
        height: {
            type: 'number',
            maximum: 1,
            exclusiveMinimum: 0,
            title: 'Height'
        }
    },
    type: 'object',
    required: ['label', 'x', 'y', 'width', 'height'],
    title: 'ExamRegionCreate'
} as const;

export const ExamRegionPublicSchema = {
    properties: {
        label: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Label'
        },
        region_type: {
            '$ref': '#/components/schemas/ExamRegionType',
            default: 'question'
        },
        page_number: {
            type: 'integer',
            minimum: 1,
            title: 'Page Number',
            default: 1
        },
        x: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'X'
        },
        y: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Y'
        },
        width: {
            type: 'number',
            maximum: 1,
            exclusiveMinimum: 0,
            title: 'Width'
        },
        height: {
            type: 'number',
            maximum: 1,
            exclusiveMinimum: 0,
            title: 'Height'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        exam_id: {
            type: 'string',
            format: 'uuid',
            title: 'Exam Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['label', 'x', 'y', 'width', 'height', 'id', 'exam_id'],
    title: 'ExamRegionPublic'
} as const;

export const ExamRegionTypeSchema = {
    type: 'string',
    enum: ['question', 'answer_area', 'header', 'other'],
    title: 'ExamRegionType'
} as const;

export const ExamRegionUpdateSchema = {
    properties: {
        label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        region_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ExamRegionType'
                },
                {
                    type: 'null'
                }
            ]
        },
        page_number: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page Number'
        },
        x: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 1,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'X'
        },
        y: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 1,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Y'
        },
        width: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 1,
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Width'
        },
        height: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 1,
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Height'
        }
    },
    type: 'object',
    title: 'ExamRegionUpdate'
} as const;

export const ExamRegionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ExamRegionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ExamRegionsPublic'
} as const;

export const ExamStatusSchema = {
    type: 'string',
    enum: ['draft', 'active', 'archived'],
    title: 'ExamStatus'
} as const;

export const ExamUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        subject: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subject'
        },
        grade_level: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade Level'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ExamStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'ExamUpdate'
} as const;

export const ExamsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ExamPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ExamsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProcessingTaskCreateSchema = {
    properties: {
        task_type: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Task Type',
            default: 'test'
        }
    },
    type: 'object',
    title: 'ProcessingTaskCreate'
} as const;

export const ProcessingTaskPublicSchema = {
    properties: {
        task_type: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Task Type'
        },
        status: {
            '$ref': '#/components/schemas/ProcessingTaskStatus',
            default: 'queued'
        },
        progress: {
            type: 'integer',
            maximum: 100,
            minimum: 0,
            title: 'Progress',
            default: 0
        },
        error_message: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By Id'
        },
        input_ref: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Input Ref'
        },
        output_ref: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Output Ref'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['task_type', 'id', 'created_by_id'],
    title: 'ProcessingTaskPublic'
} as const;

export const ProcessingTaskStatusSchema = {
    type: 'string',
    enum: ['queued', 'running', 'succeeded', 'failed'],
    title: 'ProcessingTaskStatus'
} as const;

export const StoredFilePublicSchema = {
    properties: {
        original_filename: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Original Filename'
        },
        content_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content Type'
        },
        storage_key: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Storage Key'
        },
        size_bytes: {
            type: 'integer',
            minimum: 0,
            title: 'Size Bytes'
        },
        sha256: {
            type: 'string',
            maxLength: 64,
            minLength: 64,
            title: 'Sha256'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        uploaded_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Uploaded By Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['original_filename', 'storage_key', 'size_bytes', 'sha256', 'id', 'uploaded_by_id'],
    title: 'StoredFilePublic'
} as const;

export const StudentSubmissionPublicSchema = {
    properties: {
        student_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Student Name'
        },
        student_identifier: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Student Identifier'
        },
        status: {
            '$ref': '#/components/schemas/StudentSubmissionStatus',
            default: 'registration_pending'
        },
        registration_status: {
            '$ref': '#/components/schemas/SubmissionRegistrationStatus',
            default: 'pending'
        },
        registration_quality: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 1,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Quality'
        },
        registration_notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        exam_id: {
            type: 'string',
            format: 'uuid',
            title: 'Exam Id'
        },
        stored_file_id: {
            type: 'string',
            format: 'uuid',
            title: 'Stored File Id'
        },
        stored_file: {
            '$ref': '#/components/schemas/StoredFilePublic'
        },
        page_count: {
            type: 'integer',
            title: 'Page Count',
            default: 1
        },
        registration_homography: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Homography'
        },
        registered_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registered At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'exam_id', 'stored_file_id', 'stored_file'],
    title: 'StudentSubmissionPublic'
} as const;

export const StudentSubmissionRegistrationUpdateSchema = {
    properties: {
        registration_status: {
            '$ref': '#/components/schemas/SubmissionRegistrationStatus'
        },
        registration_quality: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 1,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Quality'
        },
        registration_notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Notes'
        },
        registration_homography: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Homography'
        }
    },
    type: 'object',
    required: ['registration_status'],
    title: 'StudentSubmissionRegistrationUpdate'
} as const;

export const StudentSubmissionStatusSchema = {
    type: 'string',
    enum: ['uploaded', 'registration_pending', 'registration_failed', 'ready_for_review'],
    title: 'StudentSubmissionStatus'
} as const;

export const StudentSubmissionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/StudentSubmissionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'StudentSubmissionsPublic'
} as const;

export const SubmissionRegistrationStatusSchema = {
    type: 'string',
    enum: ['pending', 'manual_confirmed', 'failed'],
    title: 'SubmissionRegistrationStatus'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;