// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ExamsReadExamsData, ExamsReadExamsResponse, ExamsCreateExamData, ExamsCreateExamResponse, ExamsReadExamData, ExamsReadExamResponse, ExamsUpdateExamData, ExamsUpdateExamResponse, ExamsDeleteExamData, ExamsDeleteExamResponse, ExamsUploadExamFileData, ExamsUploadExamFileResponse, ExamsReadExamFilesData, ExamsReadExamFilesResponse, ExamsReadExamFileContentData, ExamsReadExamFileContentResponse, ExamsReadExamFilePageImageData, ExamsReadExamFilePageImageResponse, ExamsReadExamRegionsData, ExamsReadExamRegionsResponse, ExamsCreateExamRegionData, ExamsCreateExamRegionResponse, ExamsUpdateExamRegionData, ExamsUpdateExamRegionResponse, ExamsDeleteExamRegionData, ExamsDeleteExamRegionResponse, FilesUploadFileData, FilesUploadFileResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, TasksCreateTestTaskData, TasksCreateTestTaskResponse, TasksReadTaskData, TasksReadTaskResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse, UtilsHealthResponse } from './types.gen';

export class ExamsService {
    /**
     * Read Exams
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ExamsPublic Successful Response
     * @throws ApiError
     */
    public static readExams(data: ExamsReadExamsData = {}): CancelablePromise<ExamsReadExamsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/exams/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Create Exam
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ExamPublic Successful Response
     * @throws ApiError
     */
    public static createExam(data: ExamsCreateExamData): CancelablePromise<ExamsCreateExamResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/exams/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read Exam
     * @param data The data for the request.
     * @param data.examId
     * @returns ExamPublic Successful Response
     * @throws ApiError
     */
    public static readExam(data: ExamsReadExamData): CancelablePromise<ExamsReadExamResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/exams/{exam_id}',
            path: {
                exam_id: data.examId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update Exam
     * @param data The data for the request.
     * @param data.examId
     * @param data.requestBody
     * @returns ExamPublic Successful Response
     * @throws ApiError
     */
    public static updateExam(data: ExamsUpdateExamData): CancelablePromise<ExamsUpdateExamResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/exams/{exam_id}',
            path: {
                exam_id: data.examId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Delete Exam
     * @param data The data for the request.
     * @param data.examId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteExam(data: ExamsDeleteExamData): CancelablePromise<ExamsDeleteExamResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/exams/{exam_id}',
            path: {
                exam_id: data.examId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Upload Exam File
     * @param data The data for the request.
     * @param data.examId
     * @param data.formData
     * @returns ExamDocumentPublic Successful Response
     * @throws ApiError
     */
    public static uploadExamFile(data: ExamsUploadExamFileData): CancelablePromise<ExamsUploadExamFileResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/exams/{exam_id}/files',
            path: {
                exam_id: data.examId
            },
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read Exam Files
     * @param data The data for the request.
     * @param data.examId
     * @returns ExamDocumentsPublic Successful Response
     * @throws ApiError
     */
    public static readExamFiles(data: ExamsReadExamFilesData): CancelablePromise<ExamsReadExamFilesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/exams/{exam_id}/files',
            path: {
                exam_id: data.examId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read Exam File Content
     * @param data The data for the request.
     * @param data.examId
     * @param data.documentId
     * @param data.authorization
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readExamFileContent(data: ExamsReadExamFileContentData): CancelablePromise<ExamsReadExamFileContentResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/exams/{exam_id}/files/{document_id}/content',
            path: {
                exam_id: data.examId,
                document_id: data.documentId
            },
            headers: {
                authorization: data.authorization
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read Exam File Page Image
     * @param data The data for the request.
     * @param data.examId
     * @param data.documentId
     * @param data.pageNumber
     * @param data.authorization
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readExamFilePageImage(data: ExamsReadExamFilePageImageData): CancelablePromise<ExamsReadExamFilePageImageResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/exams/{exam_id}/files/{document_id}/pages/{page_number}/image',
            path: {
                exam_id: data.examId,
                document_id: data.documentId,
                page_number: data.pageNumber
            },
            headers: {
                authorization: data.authorization
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read Exam Regions
     * @param data The data for the request.
     * @param data.examId
     * @returns ExamRegionsPublic Successful Response
     * @throws ApiError
     */
    public static readExamRegions(data: ExamsReadExamRegionsData): CancelablePromise<ExamsReadExamRegionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/exams/{exam_id}/regions',
            path: {
                exam_id: data.examId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Create Exam Region
     * @param data The data for the request.
     * @param data.examId
     * @param data.requestBody
     * @returns ExamRegionPublic Successful Response
     * @throws ApiError
     */
    public static createExamRegion(data: ExamsCreateExamRegionData): CancelablePromise<ExamsCreateExamRegionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/exams/{exam_id}/regions',
            path: {
                exam_id: data.examId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update Exam Region
     * @param data The data for the request.
     * @param data.examId
     * @param data.regionId
     * @param data.requestBody
     * @returns ExamRegionPublic Successful Response
     * @throws ApiError
     */
    public static updateExamRegion(data: ExamsUpdateExamRegionData): CancelablePromise<ExamsUpdateExamRegionResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/exams/{exam_id}/regions/{region_id}',
            path: {
                exam_id: data.examId,
                region_id: data.regionId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Delete Exam Region
     * @param data The data for the request.
     * @param data.examId
     * @param data.regionId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteExamRegion(data: ExamsDeleteExamRegionData): CancelablePromise<ExamsDeleteExamRegionResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/exams/{exam_id}/regions/{region_id}',
            path: {
                exam_id: data.examId,
                region_id: data.regionId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class FilesService {
    /**
     * Upload File
     * @param data The data for the request.
     * @param data.formData
     * @returns StoredFilePublic Successful Response
     * @throws ApiError
     */
    public static uploadFile(data: FilesUploadFileData): CancelablePromise<FilesUploadFileResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/files/upload',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }

    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class TasksService {
    /**
     * Create Test Task
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ProcessingTaskPublic Successful Response
     * @throws ApiError
     */
    public static createTestTask(data: TasksCreateTestTaskData): CancelablePromise<TasksCreateTestTaskResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/tasks/test',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read Task
     * @param data The data for the request.
     * @param data.taskId
     * @returns ProcessingTaskPublic Successful Response
     * @throws ApiError
     */
    public static readTask(data: TasksReadTaskData): CancelablePromise<TasksReadTaskResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/tasks/{task_id}',
            path: {
                task_id: data.taskId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }

    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }

    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }

    /**
     * Health
     * @returns string Successful Response
     * @throws ApiError
     */
    public static health(): CancelablePromise<UtilsHealthResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health'
        });
    }
}