// This file is auto-generated by @hey-api/openapi-ts

export type Body_exams_preprocess_student_submission_photo = {
    file: string;
    student_name?: (string | null);
    student_identifier?: (string | null);
};

export type Body_exams_upload_exam_file = {
    file: string;
    document_type?: ExamDocumentType;
};

export type Body_exams_upload_student_submission = {
    file: string;
    student_name?: (string | null);
    student_identifier?: (string | null);
};

export type Body_files_upload_file = {
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ExamCreate = {
    title: string;
    subject?: (string | null);
    grade_level?: (string | null);
};

export type ExamDocumentPublic = {
    document_type?: ExamDocumentType;
    id: string;
    exam_id: string;
    stored_file_id: string;
    stored_file: StoredFilePublic;
    page_count?: number;
    created_at?: (string | null);
};

export type ExamDocumentsPublic = {
    data: Array<ExamDocumentPublic>;
    count: number;
};

export type ExamDocumentType = 'blank_exam' | 'answer_key';

export type ExamPublic = {
    title: string;
    subject?: (string | null);
    grade_level?: (string | null);
    status?: ExamStatus;
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ExamRegionCreate = {
    label: string;
    region_type?: ExamRegionType;
    page_number?: number;
    x: number;
    y: number;
    width: number;
    height: number;
};

export type ExamRegionPublic = {
    label: string;
    region_type?: ExamRegionType;
    page_number?: number;
    x: number;
    y: number;
    width: number;
    height: number;
    id: string;
    exam_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ExamRegionsPublic = {
    data: Array<ExamRegionPublic>;
    count: number;
};

export type ExamRegionType = 'question' | 'answer_area' | 'header' | 'other';

export type ExamRegionUpdate = {
    label?: (string | null);
    region_type?: (ExamRegionType | null);
    page_number?: (number | null);
    x?: (number | null);
    y?: (number | null);
    width?: (number | null);
    height?: (number | null);
};

export type ExamsPublic = {
    data: Array<ExamPublic>;
    count: number;
};

export type ExamStatus = 'draft' | 'active' | 'archived';

export type ExamUpdate = {
    title?: (string | null);
    subject?: (string | null);
    grade_level?: (string | null);
    status?: (ExamStatus | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProcessingTaskCreate = {
    task_type?: string;
};

export type ProcessingTaskPublic = {
    task_type: string;
    status?: ProcessingTaskStatus;
    progress?: number;
    error_message?: (string | null);
    id: string;
    created_by_id: string;
    input_ref?: ({
    [key: string]: unknown;
} | null);
    output_ref?: ({
    [key: string]: unknown;
} | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ProcessingTaskStatus = 'queued' | 'running' | 'succeeded' | 'failed';

export type StoredFilePublic = {
    original_filename: string;
    content_type?: (string | null);
    storage_key: string;
    size_bytes: number;
    sha256: string;
    id: string;
    uploaded_by_id: string;
    created_at?: (string | null);
};

export type StudentSubmissionPublic = {
    student_name?: (string | null);
    student_identifier?: (string | null);
    status?: StudentSubmissionStatus;
    registration_status?: SubmissionRegistrationStatus;
    registration_quality?: (number | null);
    registration_notes?: (string | null);
    id: string;
    exam_id: string;
    stored_file_id: string;
    stored_file: StoredFilePublic;
    page_count?: number;
    registration_homography?: ({
    [key: string]: unknown;
} | null);
    registered_at?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type StudentSubmissionRegistrationUpdate = {
    registration_status: SubmissionRegistrationStatus;
    registration_quality?: (number | null);
    registration_notes?: (string | null);
    registration_homography?: ({
    [key: string]: unknown;
} | null);
};

export type StudentSubmissionsPublic = {
    data: Array<StudentSubmissionPublic>;
    count: number;
};

export type StudentSubmissionStatus = 'uploaded' | 'registration_pending' | 'registration_failed' | 'ready_for_review';

export type SubmissionAnnotationCreate = {
    label: string;
    status?: SubmissionAnnotationStatus;
    page_number?: number;
    x: number;
    y: number;
    width: number;
    height: number;
    score?: (number | null);
    max_score?: (number | null);
    comment?: (string | null);
    exam_region_id?: (string | null);
};

export type SubmissionAnnotationPublic = {
    label: string;
    status?: SubmissionAnnotationStatus;
    page_number?: number;
    x: number;
    y: number;
    width: number;
    height: number;
    score?: (number | null);
    max_score?: (number | null);
    comment?: (string | null);
    id: string;
    submission_id: string;
    exam_region_id?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type SubmissionAnnotationsPublic = {
    data: Array<SubmissionAnnotationPublic>;
    count: number;
};

export type SubmissionAnnotationStatus = 'needs_review' | 'accepted' | 'rejected';

export type SubmissionAnnotationUpdate = {
    label?: (string | null);
    status?: (SubmissionAnnotationStatus | null);
    page_number?: (number | null);
    x?: (number | null);
    y?: (number | null);
    width?: (number | null);
    height?: (number | null);
    score?: (number | null);
    max_score?: (number | null);
    comment?: (string | null);
};

export type SubmissionRegistrationStatus = 'pending' | 'manual_confirmed' | 'failed';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ExamsReadExamsData = {
    limit?: number;
    skip?: number;
};

export type ExamsReadExamsResponse = (ExamsPublic);

export type ExamsCreateExamData = {
    requestBody: ExamCreate;
};

export type ExamsCreateExamResponse = (ExamPublic);

export type ExamsReadExamData = {
    examId: string;
};

export type ExamsReadExamResponse = (ExamPublic);

export type ExamsUpdateExamData = {
    examId: string;
    requestBody: ExamUpdate;
};

export type ExamsUpdateExamResponse = (ExamPublic);

export type ExamsDeleteExamData = {
    examId: string;
};

export type ExamsDeleteExamResponse = (Message);

export type ExamsUploadExamFileData = {
    examId: string;
    formData: Body_exams_upload_exam_file;
};

export type ExamsUploadExamFileResponse = (ExamDocumentPublic);

export type ExamsReadExamFilesData = {
    examId: string;
};

export type ExamsReadExamFilesResponse = (ExamDocumentsPublic);

export type ExamsReadExamFileContentData = {
    authorization?: (string | null);
    documentId: string;
    examId: string;
};

export type ExamsReadExamFileContentResponse = (unknown);

export type ExamsReadExamFilePageImageData = {
    authorization?: (string | null);
    documentId: string;
    examId: string;
    pageNumber: number;
};

export type ExamsReadExamFilePageImageResponse = (unknown);

export type ExamsUploadStudentSubmissionData = {
    examId: string;
    formData: Body_exams_upload_student_submission;
};

export type ExamsUploadStudentSubmissionResponse = (StudentSubmissionPublic);

export type ExamsReadStudentSubmissionsData = {
    examId: string;
};

export type ExamsReadStudentSubmissionsResponse = (StudentSubmissionsPublic);

export type ExamsPreprocessStudentSubmissionPhotoData = {
    examId: string;
    formData: Body_exams_preprocess_student_submission_photo;
};

export type ExamsPreprocessStudentSubmissionPhotoResponse = (StudentSubmissionPublic);

export type ExamsReadStudentSubmissionData = {
    examId: string;
    submissionId: string;
};

export type ExamsReadStudentSubmissionResponse = (StudentSubmissionPublic);

export type ExamsUpdateStudentSubmissionRegistrationData = {
    examId: string;
    requestBody: StudentSubmissionRegistrationUpdate;
    submissionId: string;
};

export type ExamsUpdateStudentSubmissionRegistrationResponse = (StudentSubmissionPublic);

export type ExamsCreateStudentSubmissionProcessingTaskData = {
    examId: string;
    submissionId: string;
};

export type ExamsCreateStudentSubmissionProcessingTaskResponse = (ProcessingTaskPublic);

export type ExamsReadStudentSubmissionPageImageData = {
    authorization?: (string | null);
    examId: string;
    pageNumber: number;
    submissionId: string;
};

export type ExamsReadStudentSubmissionPageImageResponse = (unknown);

export type ExamsReadStudentSubmissionTemplateRegionsData = {
    examId: string;
    pageNumber?: (number | null);
    submissionId: string;
};

export type ExamsReadStudentSubmissionTemplateRegionsResponse = (ExamRegionsPublic);

export type ExamsReadStudentSubmissionRegionCropData = {
    authorization?: (string | null);
    examId: string;
    regionId: string;
    submissionId: string;
};

export type ExamsReadStudentSubmissionRegionCropResponse = (unknown);

export type ExamsReadSubmissionAnnotationCropData = {
    annotationId: string;
    authorization?: (string | null);
    examId: string;
    submissionId: string;
};

export type ExamsReadSubmissionAnnotationCropResponse = (unknown);

export type ExamsReadSubmissionAnnotationsData = {
    examId: string;
    submissionId: string;
};

export type ExamsReadSubmissionAnnotationsResponse = (SubmissionAnnotationsPublic);

export type ExamsCreateSubmissionAnnotationData = {
    examId: string;
    requestBody: SubmissionAnnotationCreate;
    submissionId: string;
};

export type ExamsCreateSubmissionAnnotationResponse = (SubmissionAnnotationPublic);

export type ExamsUpdateSubmissionAnnotationData = {
    annotationId: string;
    examId: string;
    requestBody: SubmissionAnnotationUpdate;
    submissionId: string;
};

export type ExamsUpdateSubmissionAnnotationResponse = (SubmissionAnnotationPublic);

export type ExamsDeleteSubmissionAnnotationData = {
    annotationId: string;
    examId: string;
    submissionId: string;
};

export type ExamsDeleteSubmissionAnnotationResponse = (Message);

export type ExamsReadExamRegionsData = {
    examId: string;
};

export type ExamsReadExamRegionsResponse = (ExamRegionsPublic);

export type ExamsCreateExamRegionData = {
    examId: string;
    requestBody: ExamRegionCreate;
};

export type ExamsCreateExamRegionResponse = (ExamRegionPublic);

export type ExamsUpdateExamRegionData = {
    examId: string;
    regionId: string;
    requestBody: ExamRegionUpdate;
};

export type ExamsUpdateExamRegionResponse = (ExamRegionPublic);

export type ExamsDeleteExamRegionData = {
    examId: string;
    regionId: string;
};

export type ExamsDeleteExamRegionResponse = (Message);

export type FilesUploadFileData = {
    formData: Body_files_upload_file;
};

export type FilesUploadFileResponse = (StoredFilePublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TasksCreateTestTaskData = {
    requestBody: ProcessingTaskCreate;
};

export type TasksCreateTestTaskResponse = (ProcessingTaskPublic);

export type TasksReadTaskData = {
    taskId: string;
};

export type TasksReadTaskResponse = (ProcessingTaskPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsHealthResponse = ({
    [key: string]: (string);
});