// This file is auto-generated by @hey-api/openapi-ts

export type AddonSku = {
    id?: string;
    code: string;
    display_name: string;
    description?: (string | null);
    answer_quota: number;
    price_cents: number;
    validity_days?: number;
    published?: boolean;
    created_at?: string;
};

export type AddonSkuCreate = {
    code: string;
    display_name: string;
    description?: (string | null);
    answer_quota: number;
    price_cents: number;
    validity_days?: number;
    published?: boolean;
};

export type AdminCommerceOrderPublic = {
    id: string;
    order_no: string;
    org_id: string;
    status: CommerceOrderStatus;
    amount_cents: number;
    currency: string;
    items?: Array<CommerceOrderItemPublic>;
    created_at: string;
    paid_at?: (string | null);
    fulfilled_at?: (string | null);
    org_name: string;
};

export type AnnotationGradingStatus = 'not_started' | 'succeeded' | 'skipped_missing_answer' | 'needs_review' | 'stale';

export type AnswerPreparationItemPublic = {
    id: string;
    run_id: string;
    question_id?: (string | null);
    source_item_key: string;
    source_question_key?: (string | null);
    answer_text: string;
    max_score: number;
    rubric_text?: (string | null);
    scoring_points: Array<{
        [key: string]: unknown;
    }>;
    confidence?: (number | null);
    match_reason?: (string | null);
    status: AnswerPreparationItemStatus;
    revision_id?: (string | null);
    error_message?: (string | null);
    created_at: string;
    updated_at: string;
};

export type AnswerPreparationItemStatus = 'queued' | 'running' | 'matched' | 'conflict' | 'unmatched' | 'failed' | 'confirmed';

export type AnswerPreparationItemUpdate = {
    question_id?: (string | null);
    answer_text?: (string | null);
    max_score?: (number | string | null);
    rubric_text?: (string | null);
    scoring_points?: (Array<{
    [key: string]: unknown;
}> | null);
    confidence?: (number | null);
    match_reason?: (string | null);
    status?: (AnswerPreparationItemStatus | null);
};

export type AnswerPreparationRunCreate = {
    source_type: AnswerPreparationSource;
    document_ids?: Array<(string)>;
};

export type AnswerPreparationRunPublic = {
    id: string;
    exam_id: string;
    created_by_id: string;
    source_type: AnswerPreparationSource;
    provider: string;
    model: string;
    document_ids: Array<(string)>;
    status: WorkflowRunStatus;
    timing: {
        [key: string]: unknown;
    };
    error_message?: (string | null);
    item_count?: number;
    created_at: string;
    started_at?: (string | null);
    completed_at?: (string | null);
    confirmed_at?: (string | null);
};

export type AnswerPreparationRunsPublic = {
    data: Array<AnswerPreparationRunPublic>;
    count: number;
};

export type AnswerPreparationSource = 'model' | 'document';

export type AnswerQuotaGrantCreate = {
    answers: number;
    source?: CreditGrantSource;
    note?: (string | null);
};

export type BankTransferConfirm = {
    transaction_reference: string;
    paid_at?: (string | null);
};

export type BillingEntitlementPublic = {
    status: 'available' | 'insufficient' | 'expired' | 'not_configured';
};

export type status = 'available' | 'insufficient' | 'expired' | 'not_configured';

export type BillingRateVersion = {
    id?: string;
    version: string;
    effective_at: string;
    input_microcredits_per_million: number;
    output_microcredits_per_million: number;
    image_microcredits_per_million: number;
    internal_input_micrormb_per_million?: number;
    internal_output_micrormb_per_million?: number;
    internal_image_micrormb_per_million?: number;
    created_at?: string;
};

export type BillingRateVersionCreate = {
    version: string;
    effective_at: string;
    input_credits_per_million: number;
    output_credits_per_million: number;
    image_credits_per_million: number;
    internal_input_rmb_per_million?: number;
    internal_output_rmb_per_million?: number;
    internal_image_rmb_per_million?: number;
};

export type BillingSubscriptionPublic = {
    id: string;
    contract_no: string;
    plan_code: string;
    status: SubscriptionStatus;
    starts_at: string;
    ends_at: string;
    rate_version_id: string;
};

export type BillingSummaryPublic = {
    entitlement: 'available' | 'insufficient' | 'expired' | 'not_configured';
    subscription?: (BillingSubscriptionPublic | null);
    available_credits?: number;
    reserved_credits?: number;
    consumed_credits?: number;
    input_tokens?: number;
    output_tokens?: number;
    image_tokens?: number;
    total_tokens?: number;
    available_answers?: number;
    reserved_answers?: number;
    consumed_answers?: number;
};

export type entitlement = 'available' | 'insufficient' | 'expired' | 'not_configured';

export type BillingUsageItemPublic = {
    id: string;
    exam_id?: (string | null);
    grading_run_id?: (string | null);
    workflow_purpose: string;
    input_tokens: number;
    output_tokens: number;
    image_tokens: number;
    total_tokens: number;
    credits: number;
    status: ModelUsageStatus;
    created_at: string;
};

export type BillingUsagePublic = {
    data: Array<BillingUsageItemPublic>;
    count: number;
};

export type Body_exams_append_student_submission_pages = {
    file: string;
    preprocess?: 'auto' | 'force' | 'none';
};

export type preprocess = 'auto' | 'force' | 'none';

export type Body_exams_preprocess_student_submission_photo = {
    file: string;
    student_name?: (string | null);
    student_identifier?: (string | null);
    class_name?: (string | null);
};

export type Body_exams_upload_exam_file = {
    file: string;
    document_type?: ExamDocumentType;
    preprocess?: 'auto' | 'force' | 'none';
};

export type Body_exams_upload_exam_files = {
    files: Array<(string)>;
    document_type?: ExamDocumentType;
    preprocess?: 'auto' | 'force' | 'none';
};

export type Body_exams_upload_student_submission = {
    file: string;
    student_name?: (string | null);
    student_identifier?: (string | null);
    class_name?: (string | null);
    preprocess?: 'auto' | 'force' | 'none';
};

export type Body_files_upload_file = {
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CatalogItemPublic = {
    item_type: 'plan' | 'addon';
    code: string;
    display_name: string;
    description?: (string | null);
    price_cents: number;
    answer_quota: number;
    validity_days: number;
};

export type item_type = 'plan' | 'addon';

export type CatalogPublicationUpdate = {
    published: boolean;
};

export type ClassGroupCreate = {
    name: string;
    grade_level?: (string | null);
    org_id?: (string | null);
};

export type ClassGroupPublic = {
    name: string;
    grade_level?: (string | null);
    id: string;
    owner_id: string;
    org_id: string;
    created_at?: (string | null);
    student_count?: number;
};

export type ClassGroupsPublic = {
    data: Array<ClassGroupPublic>;
    count: number;
};

export type ClassGroupUpdate = {
    name?: (string | null);
    grade_level?: (string | null);
};

export type CommerceCatalogPublic = {
    data: Array<CatalogItemPublic>;
};

export type CommerceOrderCreate = {
    idempotency_key: string;
    items: Array<CommerceOrderLineCreate>;
};

export type CommerceOrderItemPublic = {
    item_type: string;
    sku_code: string;
    display_name: string;
    quantity: number;
    unit_price_cents: number;
    answer_quota: number;
    validity_days: number;
};

export type CommerceOrderLineCreate = {
    item_type: 'plan' | 'addon';
    code: string;
    quantity?: number;
};

export type CommerceOrderPublic = {
    id: string;
    order_no: string;
    org_id: string;
    status: CommerceOrderStatus;
    amount_cents: number;
    currency: string;
    items?: Array<CommerceOrderItemPublic>;
    created_at: string;
    paid_at?: (string | null);
    fulfilled_at?: (string | null);
};

export type CommerceOrderStatus = 'pending_payment' | 'paid' | 'fulfilled' | 'closed' | 'refunding' | 'refunded';

export type CreditGrantCreate = {
    credits: number;
    source?: CreditGrantSource;
    note?: (string | null);
};

export type CreditGrantSource = 'subscription' | 'top_up' | 'adjustment';

export type CreditLedgerItemPublic = {
    id: string;
    entry_type: string;
    amount_credits: number;
    balance_after_credits: number;
    note?: (string | null);
    created_at: string;
};

export type CreditLedgerPublic = {
    data: Array<CreditLedgerItemPublic>;
    count: number;
};

export type DocumentPageQuad = {
    label?: (string | null);
    points: Array<DocumentQuadPoint>;
};

export type DocumentQuadPoint = {
    x: number;
    y: number;
};

export type ExamAnalysisReportPublic = {
    overall: string;
    weak: string;
    polar: string;
    advice: string;
    generated_at: string;
};

export type ExamComposeRequest = {
    title: string;
    question_ids: Array<(string)>;
};

export type ExamCreate = {
    title: string;
    subject?: (string | null);
    grade_level?: (string | null);
    exam_date?: (string | null);
    description?: (string | null);
    class_ids?: (Array<(string)> | null);
    org_id?: (string | null);
};

export type ExamDocumentOrderUpdate = {
    document_ids: Array<(string)>;
};

export type ExamDocumentPublic = {
    document_type?: ExamDocumentType;
    sort_order?: number;
    id: string;
    exam_id: string;
    stored_file_id: string;
    stored_file: StoredFilePublic;
    page_count?: number;
    original_stored_file_id?: (string | null);
    preprocessing_status?: string;
    preprocessing_quality?: (number | null);
    preprocessing_metadata?: ({
    [key: string]: unknown;
} | null);
    created_at?: (string | null);
};

export type ExamDocumentQuadPreprocessRequest = {
    pages: Array<DocumentPageQuad>;
    detector?: string;
    margin_mode?: string;
};

export type ExamDocumentRecognitionRequest = {
    document_ids: Array<(string)>;
    verification_mode?: 'fast' | 'selective' | 'evidence';
};

export type verification_mode = 'fast' | 'selective' | 'evidence';

export type ExamDocumentsPublic = {
    data: Array<ExamDocumentPublic>;
    count: number;
};

export type ExamDocumentType = 'blank_exam' | 'answer_key';

export type ExamPublic = {
    title: string;
    subject?: (string | null);
    grade_level?: (string | null);
    exam_date?: (string | null);
    description?: (string | null);
    status?: ExamStatus;
    shared_grading_enabled?: boolean;
    id: string;
    owner_id: string;
    org_id: string;
    created_at?: (string | null);
    class_ids?: Array<(string)>;
    class_names?: Array<(string)>;
    is_assigned?: boolean;
};

export type ExamQuestionPublic = {
    id: string;
    exam_id: string;
    question_key: string;
    label: string;
    question_text: string;
    question_type?: (string | null);
    knowledge_point?: (string | null);
    difficulty?: (number | null);
    recognition_confidence?: (number | null);
    status: ExamQuestionStatus;
    region_ids?: Array<(string)>;
    confirmed_by_id?: (string | null);
    confirmed_at?: (string | null);
    created_at: string;
    updated_at: string;
};

export type ExamQuestionsPublic = {
    data: Array<ExamQuestionPublic>;
    count: number;
};

export type ExamQuestionStatus = 'draft' | 'confirmed';

export type ExamRegionCandidate = {
    label: string;
    region_type?: ExamRegionType;
    page_number?: number;
    x: number;
    y: number;
    width: number;
    height: number;
    confidence: number;
    source: string;
    reasons?: Array<(string)>;
};

export type ExamRegionCandidatesPublic = {
    data: Array<ExamRegionCandidate>;
    count: number;
    page_number: number;
    engine: string;
    elapsed_ms?: number;
    orientation_ms?: number;
    layout_ms?: number;
    refinement_ms?: number;
    rotation?: number;
    upright_image?: (string | null);
    provider?: (string | null);
    provider_label?: (string | null);
    requested_provider?: (string | null);
    provider_failover_count?: number;
};

export type ExamRegionCreate = {
    label: string;
    region_type?: ExamRegionType;
    page_number?: number;
    x: number;
    y: number;
    width: number;
    height: number;
    exam_document_id?: (string | null);
};

export type ExamRegionPublic = {
    label: string;
    region_type?: ExamRegionType;
    page_number?: number;
    x: number;
    y: number;
    width: number;
    height: number;
    id: string;
    exam_id: string;
    exam_document_id?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
    question_key?: (string | null);
    question_label?: (string | null);
    region_role?: (string | null);
};

export type ExamRegionsPublic = {
    data: Array<ExamRegionPublic>;
    count: number;
};

export type ExamRegionType = 'question' | 'answer_area' | 'header' | 'other';

export type ExamRegionUpdate = {
    label?: (string | null);
    region_type?: (ExamRegionType | null);
    page_number?: (number | null);
    x?: (number | null);
    y?: (number | null);
    width?: (number | null);
    height?: (number | null);
    exam_document_id?: (string | null);
};

export type ExamScoreSummaryPublic = {
    data: Array<ExamScoreSummaryRow>;
    count: number;
};

export type ExamScoreSummaryQuestion = {
    label: string;
    score?: (number | null);
    max_score?: (number | null);
    score_source?: (string | null);
    annotation_id?: (string | null);
};

export type ExamScoreSummaryRow = {
    submission_id: string;
    student_name?: (string | null);
    student_identifier?: (string | null);
    class_name?: (string | null);
    total_score?: (number | null);
    total_max_score?: (number | null);
    questions?: Array<ExamScoreSummaryQuestion>;
    status?: StudentSubmissionStatus;
    registration_status?: SubmissionRegistrationStatus;
    registration_quality?: (number | null);
    registration_notes?: (string | null);
    page_count?: (number | null);
    pending_review_count?: number;
};

export type ExamsPublic = {
    data: Array<ExamPublic>;
    count: number;
};

export type ExamStatus = 'draft' | 'active' | 'archived';

export type ExamUpdate = {
    title?: (string | null);
    subject?: (string | null);
    grade_level?: (string | null);
    exam_date?: (string | null);
    description?: (string | null);
    status?: (ExamStatus | null);
    class_ids?: (Array<(string)> | null);
};

export type ExamWorkflowStepPublic = {
    code: string;
    label: string;
    status: 'pending' | 'active' | 'completed' | 'blocked';
    count?: number;
};

export type status2 = 'pending' | 'active' | 'completed' | 'blocked';

export type ExamWorkflowSummaryPublic = {
    exam_id: string;
    next_action: string;
    next_label: string;
    next_path: string;
    message: string;
    steps: Array<ExamWorkflowStepPublic>;
};

export type FunctionModelAssignmentPublic = {
    purpose: string;
    default_canonical_model: string;
    updated_at: string;
};

export type FunctionModelAssignmentUpdate = {
    canonical_model: string;
};

export type GradingAssigneePublic = {
    user_id: string;
    user_name: string;
    class_ids?: Array<(string)>;
};

export type GradingAssignmentClassPublic = {
    class_id: string;
    class_name: string;
};

export type GradingAssignmentEntry = {
    class_id: string;
    user_id: string;
};

export type GradingAssignmentItemPublic = {
    class_id: string;
    class_name: string;
    user_id: string;
    user_name?: (string | null);
};

export type GradingAssignmentsPublic = {
    enabled: boolean;
    assignments?: Array<GradingAssignmentItemPublic>;
    unassigned?: Array<GradingAssignmentClassPublic>;
    candidates?: Array<GradingAssigneePublic>;
};

export type GradingAssignmentsUpdate = {
    enabled: boolean;
    assignments?: Array<GradingAssignmentEntry>;
};

export type GradingAuditEventPublic = {
    id: string;
    grading_run_id?: (string | null);
    submission_id: string;
    annotation_id: string;
    operator_id?: (string | null);
    source: string;
    old_score?: (number | null);
    new_score?: (number | null);
    old_comment?: (string | null);
    new_comment?: (string | null);
    reason?: (string | null);
    metadata_json: {
        [key: string]: unknown;
    };
    created_at: string;
};

export type GradingItemStatus = 'queued' | 'extracting' | 'grading' | 'completed' | 'needs_review' | 'failed';

export type GradingReviewItem = {
    submission_id: string;
    student_name?: (string | null);
    student_identifier?: (string | null);
    annotation_id?: (string | null);
    label?: (string | null);
    score?: (number | null);
    max_score?: (number | null);
    confidence?: (number | null);
    risk: string;
    priority: number;
};

export type GradingRunCreate = {
    exam_id: string;
    submission_ids?: Array<(string)>;
    review_threshold?: (number | null);
    max_concurrency?: (number | null);
    max_parallel_submissions?: (number | null);
    max_concurrency_per_submission?: (number | null);
    recognition_run_id?: (string | null);
};

export type GradingRunPublic = {
    id: string;
    exam_id: string;
    created_by_id: string;
    provider: string;
    model: string;
    fallback_models: Array<(string)>;
    answer_version: number;
    status: GradingRunStatus;
    total_submissions: number;
    completed_count: number;
    review_count: number;
    failed_count: number;
    average_confidence?: (number | null);
    total_items?: number;
    completed_items?: number;
    extracted_items?: number;
    objective_items?: number;
    subjective_items?: number;
    current_concurrency?: number;
    throttle_count?: number;
    config_snapshot: {
        [key: string]: unknown;
    };
    timing?: {
        [key: string]: unknown;
    };
    error_message?: (string | null);
    estimated_credits?: number;
    reserved_credits?: number;
    settled_credits?: number;
    billing_status?: string;
    created_at: string;
    started_at?: (string | null);
    completed_at?: (string | null);
};

export type GradingRunsPublic = {
    data: Array<GradingRunPublic>;
    count: number;
};

export type GradingRunStatus = 'awaiting_credits' | 'queued' | 'running' | 'completed' | 'completed_with_errors' | 'failed';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InvoiceApplicationCreate = {
    order_id: string;
    title: string;
    tax_number: string;
    email: string;
};

export type InvoiceApplicationPublic = {
    id: string;
    order_id: string;
    org_id: string;
    title: string;
    tax_number: string;
    email: string;
    amount_cents: number;
    status: InvoiceStatus;
    invoice_no?: (string | null);
    reject_reason?: (string | null);
    created_at: string;
};

export type InvoiceReview = {
    status: 'approved' | 'issued' | 'rejected';
    invoice_no?: (string | null);
    reject_reason?: (string | null);
};

export type status3 = 'approved' | 'issued' | 'rejected';

export type InvoiceStatus = 'submitted' | 'approved' | 'issued' | 'rejected';

export type MarkingRecognitionImport = {
    document_ids: Array<(string)>;
    covered_page_ids: Array<(string)>;
    results: Array<{
        [key: string]: unknown;
    }>;
    blocks: Array<{
        [key: string]: unknown;
    }>;
    layouts?: Array<{
        [key: string]: unknown;
    }>;
    timing?: {
        [key: string]: unknown;
    };
};

export type Message = {
    message: string;
};

export type ModelRoutePolicyPublic = {
    id: string;
    purpose: string;
    canonical_model: string;
    enabled: boolean;
    max_attempts: number;
    routing_mode: string;
    sticky_scope: string;
    targets: Array<ModelRouteTargetPublic>;
};

export type ModelRoutePolicyUpsert = {
    canonical_model: string;
    enabled?: boolean;
    max_attempts?: number;
    routing_mode?: 'balanced' | 'cost_first' | 'latency_first';
    targets: Array<ModelRouteTargetInput>;
};

export type routing_mode = 'balanced' | 'cost_first' | 'latency_first';

export type ModelRouteTargetInput = {
    mapping_id: string;
    priority?: number;
    weight?: number;
    enabled?: boolean;
};

export type ModelRouteTargetPublic = {
    id: string;
    mapping_id: string;
    channel_id: string;
    channel_code: string;
    canonical_model: string;
    upstream_model: string;
    protocol: ProviderProtocol;
    base_url: string;
    priority: number;
    weight: number;
    enabled: boolean;
    cost_rmb_per_million?: (number | null);
};

export type ModelRouteVersionPublic = {
    id: string;
    policy_id: string;
    version: number;
    status: ModelRouteVersionStatus;
    max_attempts: number;
    routing_mode: string;
    sticky_scope: string;
    created_at: string;
    published_at?: (string | null);
    targets?: Array<ModelRouteTargetPublic>;
};

export type ModelRouteVersionStatus = 'draft' | 'published' | 'retired';

export type ModelUsageStatus = 'succeeded' | 'failed' | 'missing_usage';

export type NewApiBillingSyncPublic = {
    batch: ReconciliationBatchPublic;
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OfferingRateVersionCreate = {
    version: string;
    effective_at: string;
    input_credits_per_million: number;
    output_credits_per_million: number;
    image_credits_per_million: number;
    target_margin_percent?: number;
    minimum_margin_percent?: number;
};

export type OfferingRateVersionPublic = {
    id: string;
    offering_id: string;
    version: string;
    effective_at: string;
    input_credits_per_million: number;
    output_credits_per_million: number;
    image_credits_per_million: number;
    target_margin_percent: number;
    minimum_margin_percent: number;
    margin_valid: boolean;
    created_at: string;
};

export type OrganizationRiskState = 'normal' | 'throttled' | 'blocked' | 'frozen';

/**
 * 学校服务状态；状态本身决定账号和业务入口是否可用。
 */
export type OrganizationServiceState = 'active' | 'read_only' | 'frozen' | 'deleting';

export type OrganizationSignupCompleted = {
    access_token: string;
    token_type?: string;
    organization: SignupOrganizationPublic;
    trial_ends_at: string;
    answer_quota: number;
};

export type OrganizationSignupCreate = {
    organization_type: OrganizationType;
    organization_name: string;
    contact_name: string;
    email: string;
    password: string;
    turnstile_token: string;
};

export type OrganizationSignupRequested = {
    message: string;
    expires_in_seconds: number;
};

export type OrganizationSignupResend = {
    email: string;
    turnstile_token: string;
};

export type OrganizationSignupVerify = {
    token: string;
};

export type OrganizationType = 'school' | 'training' | 'other';

export type OrganizationUsagePolicyPublic = {
    org_id: string;
    risk_state: OrganizationRiskState;
    calls_per_minute: number;
    max_running_jobs: number;
    max_model_concurrency: number;
    max_job_credits: number;
    daily_credit_cap: number;
    monthly_credit_cap: number;
    reason?: (string | null);
    updated_at: string;
};

export type OrganizationUsagePolicyUpdate = {
    risk_state?: (OrganizationRiskState | null);
    calls_per_minute?: (number | null);
    max_running_jobs?: (number | null);
    max_model_concurrency?: (number | null);
    max_job_credits?: (number | null);
    daily_credit_cap?: (number | null);
    monthly_credit_cap?: (number | null);
    reason?: (string | null);
};

export type OrgOnboardingPublic = {
    class_count: number;
    teacher_count: number;
    student_count: number;
    teacher_exam_count: number;
};

export type OrgSettingsPublic = {
    name: string;
    code: string;
    organization_type: OrganizationType;
    exam_sharing_enabled: boolean;
    contact_name?: (string | null);
};

export type OrgSettingsUpdate = {
    contact_name?: (string | null);
    exam_sharing_enabled?: (boolean | null);
};

export type PlanVersion = {
    id?: string;
    code: string;
    version: number;
    display_name: string;
    description?: (string | null);
    annual_price_cents: number;
    included_answers: number;
    validity_days?: number;
    published?: boolean;
    created_at?: string;
};

export type PlanVersionCreate = {
    code: string;
    version: number;
    display_name: string;
    description?: (string | null);
    annual_price_cents: number;
    included_answers: number;
    validity_days?: number;
    published?: boolean;
};

/**
 * 平台人员目录中的一条账号或学生名册记录。
 */
export type PlatformDirectoryItem = {
    record_type: string;
    record_id: string;
    user_id?: (string | null);
    student_id?: (string | null);
    name: string;
    role: UserRole;
    email?: (string | null);
    person_no?: (string | null);
    org_id: string;
    org_name: string;
    class_id?: (string | null);
    class_name?: (string | null);
    class_names?: Array<(string)>;
    link_status: string;
    is_active?: (boolean | null);
    created_at?: (string | null);
};

export type PlatformDirectoryPublic = {
    data: Array<PlatformDirectoryItem>;
    count: number;
};

export type PlatformModelOfferingCreate = {
    code: string;
    display_name: string;
    description?: (string | null);
    scope: SchoolModelScope;
    provider_code?: string;
    canonical_model: string;
    published?: boolean;
    school_selectable?: boolean;
    sort_order?: number;
};

export type PlatformModelOfferingPublic = {
    id: string;
    code: string;
    display_name: string;
    description?: (string | null);
    scope: SchoolModelScope;
    provider_code: string;
    canonical_model: string;
    published: boolean;
    school_selectable: boolean;
    sort_order: number;
    mapped_channel_count?: number;
    route_purposes?: Array<(string)>;
    created_at: string;
    updated_at: string;
};

export type PlatformModelOfferingsPublic = {
    data: Array<PlatformModelOfferingPublic>;
    count: number;
};

export type PlatformModelOfferingUpdate = {
    display_name?: (string | null);
    description?: (string | null);
    scope?: (SchoolModelScope | null);
    provider_code?: (string | null);
    canonical_model?: (string | null);
    published?: (boolean | null);
    school_selectable?: (boolean | null);
    sort_order?: (number | null);
};

export type PlatformModelUsageBreakdownItem = {
    key: string;
    label: string;
    org_id?: (string | null);
    calls?: number;
    failed_calls?: number;
    total_tokens?: number;
    customer_credits?: number;
    internal_cost_rmb?: number;
    upstream_cost_rmb?: number;
    reconciled_calls?: number;
    average_latency_ms?: number;
};

export type PlatformModelUsageEventPublic = {
    id: string;
    org_id: string;
    org_name: string;
    exam_id?: (string | null);
    grading_run_id?: (string | null);
    resource_id: string;
    workflow_purpose: string;
    purpose_label: string;
    requested_provider: string;
    requested_model: string;
    actual_provider?: (string | null);
    actual_model?: (string | null);
    channel_id?: (string | null);
    channel_name?: (string | null);
    attempt_number: number;
    attempt_kind: string;
    fallback_used: boolean;
    http_status?: (number | null);
    error_code?: (string | null);
    input_tokens: number;
    output_tokens: number;
    image_tokens: number;
    cached_input_tokens: number;
    reasoning_tokens: number;
    total_tokens: number;
    latency_ms: number;
    status: ModelUsageStatus;
    customer_credits: number;
    internal_cost_rmb: number;
    upstream_cost_rmb?: (number | null);
    cost_variance_rmb?: (number | null);
    reconciliation_status: UsageReconciliationStatus;
    created_at: string;
};

export type PlatformModelUsageEventsPublic = {
    data: Array<PlatformModelUsageEventPublic>;
    count: number;
};

export type PlatformModelUsageOverviewPublic = {
    days: number;
    since: string;
    summary: PlatformModelUsageSummaryPublic;
    organizations: Array<PlatformModelUsageBreakdownItem>;
    purposes: Array<PlatformModelUsageBreakdownItem>;
    models: Array<PlatformModelUsageBreakdownItem>;
    daily: Array<PlatformModelUsageBreakdownItem>;
};

export type PlatformModelUsageSummaryPublic = {
    calls?: number;
    succeeded_calls?: number;
    failed_calls?: number;
    missing_usage_calls?: number;
    success_rate?: number;
    input_tokens?: number;
    output_tokens?: number;
    image_tokens?: number;
    reasoning_tokens?: number;
    total_tokens?: number;
    customer_credits?: number;
    internal_cost_rmb?: number;
    upstream_cost_rmb?: number;
    reconciled_internal_cost_rmb?: number;
    cost_variance_rmb?: number;
    reconciled_calls?: number;
    unreconciled_calls?: number;
    average_latency_ms?: number;
    fallback_calls?: number;
};

export type PlatformOrgCreate = {
    name: string;
    code: string;
    contact_name?: (string | null);
    owner?: (PlatformOrgOwnerCreate | null);
};

export type PlatformOrgDetail = {
    id: string;
    name: string;
    code: string;
    status: OrganizationServiceState;
    exam_sharing_enabled: boolean;
    contact_name?: (string | null);
    created_at?: (string | null);
    exam_count?: number;
    student_count?: number;
    teacher_count?: number;
    class_count?: number;
    account_count?: number;
    unbound_student_count?: number;
    users?: Array<PlatformOrgUserItem>;
};

export type PlatformOrgListItem = {
    id: string;
    name: string;
    code: string;
    status: OrganizationServiceState;
    exam_count?: number;
    student_count?: number;
    teacher_count?: number;
    class_count?: number;
    account_count?: number;
    unbound_student_count?: number;
    contact_name?: (string | null);
    owner_name?: (string | null);
    owner_email?: (string | null);
    created_at?: (string | null);
};

/**
 * 新建学校时附带的首个 school_owner 账号。
 */
export type PlatformOrgOwnerCreate = {
    email: string;
    full_name?: (string | null);
    password: string;
};

export type PlatformOrgsPublic = {
    data: Array<PlatformOrgListItem>;
    count: number;
};

export type PlatformOrgUpdate = {
    name?: (string | null);
    code?: (string | null);
    status?: (OrganizationServiceState | null);
    contact_name?: (string | null);
};

export type PlatformOrgUserItem = {
    id: string;
    email: string;
    full_name?: (string | null);
    role: UserRole;
    is_active: boolean;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProcessingTaskCreate = {
    task_type?: string;
};

export type ProcessingTaskPublic = {
    task_type: string;
    status?: ProcessingTaskStatus;
    progress?: number;
    error_message?: (string | null);
    id: string;
    created_by_id: string;
    input_ref?: ({
    [key: string]: unknown;
} | null);
    output_ref?: ({
    [key: string]: unknown;
} | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ProcessingTaskStatus = 'queued' | 'running' | 'succeeded' | 'failed';

export type ProviderBillingCredentialUpdate = {
    access_token: string;
    user_id?: (number | null);
};

export type ProviderChannelCreate = {
    code: string;
    display_name: string;
    kind: ProviderChannelKind;
    protocol?: ProviderProtocol;
    base_url: string;
    api_key?: (string | null);
    status?: (ProviderChannelStatus | null);
    enabled?: boolean;
    risk_acknowledged?: boolean;
    priority?: number;
    weight?: number;
    max_concurrency?: number;
    timeout_seconds?: number;
};

export type ProviderChannelKind = 'official_api' | 'authorized_relay' | 'new_api' | 'sub2api' | 'cli_proxy_api' | 'custom';

export type ProviderChannelPublic = {
    id: string;
    code: string;
    display_name: string;
    kind: ProviderChannelKind;
    protocol: ProviderProtocol;
    base_url: string;
    status: ProviderChannelStatus;
    enabled: boolean;
    risk_acknowledged: boolean;
    priority: number;
    weight: number;
    max_concurrency: number;
    timeout_seconds: number;
    credential_configured?: boolean;
    credential_fingerprint?: (string | null);
    credential_last_four?: (string | null);
    billing_credential_configured?: boolean;
    billing_credential_last_four?: (string | null);
    billing_user_id?: (number | null);
    health_status?: ProviderHealthStatus;
    created_at: string;
    updated_at: string;
};

export type ProviderChannelsPublic = {
    data: Array<ProviderChannelPublic>;
    count: number;
};

export type ProviderChannelStatus = 'draft' | 'active' | 'draining' | 'disabled';

export type ProviderChannelTestRequest = {
    canonical_model: string;
};

export type ProviderChannelTestResult = {
    ok: boolean;
    channel_id: string;
    canonical_model: string;
    upstream_model?: (string | null);
    latency_ms?: number;
    usage_present?: boolean;
    error?: (string | null);
};

export type ProviderChannelUpdate = {
    display_name?: (string | null);
    kind?: (ProviderChannelKind | null);
    protocol?: (ProviderProtocol | null);
    base_url?: (string | null);
    status?: (ProviderChannelStatus | null);
    enabled?: (boolean | null);
    risk_acknowledged?: (boolean | null);
    priority?: (number | null);
    weight?: (number | null);
    max_concurrency?: (number | null);
    timeout_seconds?: (number | null);
};

export type ProviderCredentialUpdate = {
    api_key: string;
};

export type ProviderHealthStatus = 'unknown' | 'healthy' | 'degraded' | 'open' | 'disabled';

export type ProviderInternalRateVersionCreate = {
    canonical_model: string;
    version: string;
    effective_at: string;
    input_rmb_per_million?: number;
    output_rmb_per_million?: number;
    image_rmb_per_million?: number;
    cached_input_rmb_per_million?: number;
};

export type ProviderInternalRateVersionPublic = {
    id: string;
    channel_id: string;
    canonical_model: string;
    version: string;
    effective_at: string;
    input_rmb_per_million: number;
    output_rmb_per_million: number;
    image_rmb_per_million: number;
    cached_input_rmb_per_million: number;
    created_at: string;
};

export type ProviderModelDiscoveryResult = {
    channel_id: string;
    models: Array<(string)>;
    count: number;
};

export type ProviderModelMappingCreate = {
    canonical_model: string;
    upstream_model: string;
    supports_vision?: boolean;
    supports_structured_output?: boolean;
    enabled?: boolean;
};

export type ProviderModelMappingPublic = {
    id: string;
    channel_id: string;
    canonical_model: string;
    upstream_model: string;
    supports_vision: boolean;
    supports_structured_output: boolean;
    usage_metering_verified: boolean;
    usage_verified_at?: (string | null);
    enabled: boolean;
    created_at: string;
    updated_at: string;
};

export type ProviderModelMappingUpdate = {
    upstream_model?: (string | null);
    supports_vision?: (boolean | null);
    supports_structured_output?: (boolean | null);
    enabled?: (boolean | null);
};

export type ProviderProtocol = 'openai_chat' | 'openai_responses';

export type ProviderStatus = {
    name: string;
    configured: boolean;
};

export type QuestionBankEntryPublic = {
    question_id: string;
    exam_id: string;
    exam_title: string;
    question_key: string;
    label: string;
    question_text: string;
    question_type?: (string | null);
    knowledge_point?: (string | null);
    difficulty?: (number | null);
    max_score?: (number | null);
};

export type QuestionBankPublic = {
    data: Array<QuestionBankEntryPublic>;
    count: number;
};

export type QuestionRecognitionItemPublic = {
    id: string;
    run_id: string;
    source_item_key: string;
    question_key: string;
    label: string;
    question_text: string;
    student_answer_text?: (string | null);
    question_type?: (string | null);
    knowledge_point?: (string | null);
    difficulty?: (number | null);
    confidence?: (number | null);
    notes?: (string | null);
    region_ids: Array<(string)>;
    region_snapshots: Array<{
        [key: string]: unknown;
    }>;
    status: QuestionRecognitionItemStatus;
    confirmed_question_id?: (string | null);
    created_at: string;
    updated_at: string;
};

export type QuestionRecognitionItemStatus = 'draft' | 'confirmed' | 'excluded';

export type QuestionRecognitionItemUpdate = {
    question_key?: (string | null);
    label?: (string | null);
    question_text?: (string | null);
    student_answer_text?: (string | null);
    question_type?: (string | null);
    knowledge_point?: (string | null);
    difficulty?: (number | null);
    confidence?: (number | null);
    notes?: (string | null);
    region_ids?: (Array<(string)> | null);
    status?: (QuestionRecognitionItemStatus | null);
};

export type QuestionRecognitionRunCreate = {
    document_ids: Array<(string)>;
};

export type QuestionRecognitionRunPublic = {
    id: string;
    exam_id: string;
    created_by_id: string;
    provider: string;
    model: string;
    engine: string;
    status: WorkflowRunStatus;
    document_ids: Array<(string)>;
    timing: {
        [key: string]: unknown;
    };
    error_message?: (string | null);
    item_count?: number;
    created_at: string;
    started_at?: (string | null);
    completed_at?: (string | null);
    confirmed_at?: (string | null);
};

export type QuestionRecognitionRunsPublic = {
    data: Array<QuestionRecognitionRunPublic>;
    count: number;
};

export type RecognitionItemPublic = {
    item_id: string;
    submission_id: string;
    exam_region_id: string;
    label: string;
    status: GradingItemStatus;
    question_text?: (string | null);
    student_answer?: (string | null);
    final_answer?: (string | null);
    confidence?: (number | null);
    notes?: Array<(string)>;
    printed_question_marks?: Array<{
        [key: string]: (string);
    }>;
    answer_entries?: Array<{
        [key: string]: unknown;
    }>;
    unassigned_evidence?: Array<(string)>;
    grading_answer?: (string | null);
    grading_eligible?: boolean;
    answer_verification?: {
        [key: string]: unknown;
    };
    error_message?: (string | null);
};

export type RecognitionItemUpdate = {
    question_text?: (string | null);
    student_answer?: (string | null);
    final_answer?: (string | null);
    confidence?: (number | null);
    notes?: (Array<(string)> | null);
    approve_for_grading?: (boolean | null);
    approval_source?: (string | null);
};

export type RecognitionRunCreate = {
    exam_id: string;
    submission_id: string;
    max_concurrency?: number;
    verification_mode?: 'fast' | 'selective' | 'evidence';
};

export type ReconciliationBatchPublic = {
    id: string;
    channel_id: string;
    source: string;
    period_start: string;
    period_end: string;
    row_count: number;
    fetched_count: number;
    ignored_count: number;
    matched_count: number;
    mismatch_count: number;
    upstream_system_name?: (string | null);
    upstream_version?: (string | null);
    upstream_total_granted_quota: number;
    upstream_total_used_quota: number;
    upstream_total_available_quota: number;
    upstream_total_used_rmb: number;
    quota_per_unit: number;
    usd_exchange_rate: number;
    unlimited_quota: boolean;
    created_at: string;
};

export type ReconciliationImport = {
    source: 'api' | 'csv';
    period_start: string;
    period_end: string;
    rows: Array<ReconciliationRowInput>;
};

export type source = 'api' | 'csv';

export type ReconciliationRowInput = {
    upstream_request_id: string;
    input_tokens?: number;
    output_tokens?: number;
    cost_rmb?: number;
};

export type RefundRequestCreate = {
    order_id: string;
    amount_cents: number;
    reason: string;
};

export type RefundRequestPublic = {
    id: string;
    order_id: string;
    org_id: string;
    amount_cents: number;
    reason: string;
    status: RefundStatus;
    review_note?: (string | null);
    created_at: string;
};

export type RefundReview = {
    status: 'approved' | 'rejected' | 'processing' | 'succeeded' | 'failed';
    review_note?: (string | null);
};

export type status4 = 'approved' | 'rejected' | 'processing' | 'succeeded' | 'failed';

export type RefundStatus = 'requested' | 'approved' | 'processing' | 'succeeded' | 'rejected' | 'failed';

export type SchoolModelOptionPublic = {
    id: string;
    code: string;
    display_name: string;
    description?: (string | null);
    scope: SchoolModelScope;
};

export type SchoolModelScope = 'vision' | 'reference_answer' | 'grading';

export type SchoolModelScopePublic = {
    scope: SchoolModelScope;
    selected_option_id?: (string | null);
    options?: Array<SchoolModelOptionPublic>;
};

export type SchoolModelSelectionUpdate = {
    offering_id: string;
};

export type SchoolModelSettingsPublic = {
    scopes: Array<SchoolModelScopePublic>;
};

export type ScoreReleaseCreate = {
    reason?: string;
};

export type ScoreReleasePublic = {
    id: string;
    exam_id: string;
    version: number;
    status: ScoreReleaseStatus;
    item_count?: number;
    published_by_id?: (string | null);
    reason: string;
    published_at: string;
};

export type ScoreReleaseStatus = 'published' | 'superseded';

export type SignupOrganizationPublic = {
    id: string;
    code: string;
    name: string;
    organization_type: OrganizationType;
};

export type StandardAnswerCreate = {
    answer_text: string;
    max_score: number;
    rubric_text?: (string | null);
    scoring_points?: Array<{
        [key: string]: unknown;
    }>;
    status?: StandardAnswerStatus;
    exam_region_id: string;
};

export type StandardAnswerPublic = {
    answer_text: string;
    max_score: number;
    rubric_text?: (string | null);
    scoring_points?: Array<{
        [key: string]: unknown;
    }>;
    status?: StandardAnswerStatus;
    id: string;
    exam_id: string;
    exam_region_id?: (string | null);
    question_id?: (string | null);
    current_revision_id?: (string | null);
    version?: number;
    source_provider?: (string | null);
    source_model?: (string | null);
    generation_confidence?: (number | null);
    answer_hash?: (string | null);
    published_at?: (string | null);
    published_by_id?: (string | null);
    question_text?: (string | null);
    question_type?: (string | null);
    rubric_config?: {
        [key: string]: unknown;
    };
    validation_report?: {
        [key: string]: unknown;
    };
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type StandardAnswerPublishRequest = {
    revision_ids?: Array<(string)>;
};

export type StandardAnswerRevisionPublic = {
    id: string;
    standard_answer_id: string;
    question_id: string;
    revision_number: number;
    question_key: string;
    question_text: string;
    question_type?: (string | null);
    answer_text: string;
    max_score: number;
    rubric_text?: (string | null);
    scoring_points: Array<{
        [key: string]: unknown;
    }>;
    source_provider?: (string | null);
    source_model?: (string | null);
    generation_confidence?: (number | null);
    content_hash: string;
    status: StandardAnswerRevisionStatus;
    created_by_id: string;
    published_by_id?: (string | null);
    preparation_item_id?: (string | null);
    created_at: string;
    published_at?: (string | null);
};

export type StandardAnswerRevisionsPublic = {
    data: Array<StandardAnswerRevisionPublic>;
    count: number;
};

export type StandardAnswerRevisionStatus = 'draft' | 'published';

export type StandardAnswersPublic = {
    data: Array<StandardAnswerPublic>;
    count: number;
};

export type StandardAnswerStatus = 'draft' | 'ready';

export type StandardAnswerUpdate = {
    answer_text?: (string | null);
    max_score?: (number | null);
    rubric_text?: (string | null);
    scoring_points?: (Array<{
    [key: string]: unknown;
}> | null);
    status?: (StandardAnswerStatus | null);
};

export type StoredFilePublic = {
    original_filename: string;
    content_type?: (string | null);
    storage_key: string;
    size_bytes: number;
    sha256: string;
    id: string;
    uploaded_by_id: string;
    created_at?: (string | null);
};

export type StudentBatchCreate = {
    rows: Array<StudentBatchRow>;
    create_accounts?: boolean;
    dry_run?: boolean;
};

export type StudentBatchResult = {
    created?: number;
    skipped?: number;
    accounts_created?: number;
    rows?: Array<StudentBatchRowResult>;
    errors?: Array<StudentBatchRowResult>;
};

/**
 * 花名册批量导入的单行（前端把 CSV/粘贴文本解析成 rows 传入）。
 */
export type StudentBatchRow = {
    name: string;
    student_no?: (string | null);
};

export type StudentBatchRowResult = {
    name: string;
    student_no?: (string | null);
    action: string;
    message?: (string | null);
};

export type StudentBindAccount = {
    user_id: string;
};

export type StudentCreate = {
    name: string;
    student_no?: (string | null);
};

export type StudentExamListItemPublic = {
    exam_id: string;
    title: string;
    subject?: (string | null);
    grade_level?: (string | null);
    exam_date?: (string | null);
    class_name?: (string | null);
    total_score?: (number | null);
    total_max_score?: (number | null);
    class_rank?: (number | null);
    class_size?: number;
    question_count?: number;
    pending_review_count?: number;
};

export type StudentExamListPublic = {
    data: Array<StudentExamListItemPublic>;
    count: number;
};

export type StudentExamReportPublic = {
    exam_id: string;
    title: string;
    subject?: (string | null);
    grade_level?: (string | null);
    exam_date?: (string | null);
    class_name?: (string | null);
    student_name?: (string | null);
    total_score?: (number | null);
    total_max_score?: (number | null);
    class_rank?: (number | null);
    class_size?: number;
    questions?: Array<StudentExamReportQuestion>;
};

export type StudentExamReportQuestion = {
    label: string;
    score?: (number | null);
    max_score?: (number | null);
    score_source?: (string | null);
    comment?: (string | null);
    suggested_comment?: (string | null);
};

export type StudentPublic = {
    name: string;
    student_no?: (string | null);
    id: string;
    class_id: string;
    user_id?: (string | null);
    account_email?: (string | null);
    created_at?: (string | null);
};

export type StudentsPublic = {
    data: Array<StudentPublic>;
    count: number;
};

export type StudentSubmissionPublic = {
    student_name?: (string | null);
    student_identifier?: (string | null);
    class_name?: (string | null);
    status?: StudentSubmissionStatus;
    registration_status?: SubmissionRegistrationStatus;
    registration_quality?: (number | null);
    registration_notes?: (string | null);
    id: string;
    exam_id: string;
    stored_file_id: string;
    stored_file: StoredFilePublic;
    page_count?: number;
    original_stored_file_id?: (string | null);
    student_id?: (string | null);
    registration_homography?: ({
    [key: string]: unknown;
} | null);
    registered_at?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type StudentSubmissionRegistrationUpdate = {
    registration_status: SubmissionRegistrationStatus;
    registration_quality?: (number | null);
    registration_notes?: (string | null);
    registration_homography?: ({
    [key: string]: unknown;
} | null);
};

export type StudentSubmissionsPublic = {
    data: Array<StudentSubmissionPublic>;
    count: number;
};

export type StudentSubmissionStatus = 'uploaded' | 'registration_pending' | 'registration_failed' | 'ready_for_review';

export type StudentUpdate = {
    name?: (string | null);
    student_no?: (string | null);
};

export type SubmissionAnnotationCreate = {
    label: string;
    status?: SubmissionAnnotationStatus;
    page_number?: number;
    x: number;
    y: number;
    width: number;
    height: number;
    score?: (number | null);
    max_score?: (number | null);
    comment?: (string | null);
    ocr_text?: (string | null);
    ocr_confidence?: (number | null);
    ocr_status?: string;
    ocr_engine?: (string | null);
    exam_region_id?: (string | null);
};

export type SubmissionAnnotationPublic = {
    label: string;
    status?: SubmissionAnnotationStatus;
    page_number?: number;
    x: number;
    y: number;
    width: number;
    height: number;
    score?: (number | null);
    max_score?: (number | null);
    comment?: (string | null);
    ocr_text?: (string | null);
    ocr_confidence?: (number | null);
    ocr_status?: string;
    ocr_engine?: (string | null);
    id: string;
    submission_id: string;
    exam_region_id?: (string | null);
    suggested_score?: (number | null);
    suggested_comment?: (string | null);
    grading_confidence?: (number | null);
    grading_reasons?: Array<{
        [key: string]: unknown;
    }>;
    grading_status?: AnnotationGradingStatus;
    answer_key_updated_at?: (string | null);
    score_source?: (string | null);
    model_score?: (number | null);
    model_confidence?: (number | null);
    grading_version?: (string | null);
    grading_evidence?: Array<{
        [key: string]: unknown;
    }>;
    auto_published_at?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type SubmissionAnnotationsPublic = {
    data: Array<SubmissionAnnotationPublic>;
    count: number;
};

export type SubmissionAnnotationStatus = 'needs_review' | 'accepted' | 'rejected';

export type SubmissionAnnotationUpdate = {
    label?: (string | null);
    status?: (SubmissionAnnotationStatus | null);
    page_number?: (number | null);
    x?: (number | null);
    y?: (number | null);
    width?: (number | null);
    height?: (number | null);
    score?: (number | null);
    max_score?: (number | null);
    comment?: (string | null);
    audit_reason?: (string | null);
};

export type SubmissionRegistrationStatus = 'pending' | 'manual_confirmed' | 'auto_confirmed' | 'failed';

export type SubscriptionStatus = 'draft' | 'active' | 'expired' | 'suspended';

export type SubscriptionUpsert = {
    contract_no: string;
    plan_code: string;
    status: SubscriptionStatus;
    starts_at: string;
    ends_at: string;
    rate_version_id: string;
};

export type SystemConfigPublic = {
    vision_provider: string;
    vision_model: string;
    grading_provider: string;
    grading_model: string;
    region_provider: string;
    region_model: string;
    recognition_provider: string;
    recognition_model: string;
    fallback_models: Array<(string)>;
    vision_fallback_models: Array<(string)>;
    reasoning_fallback_models: Array<(string)>;
    review_threshold: number;
    max_concurrency: number;
    providers: Array<ProviderStatus>;
};

export type SystemConfigUpdate = {
    vision_provider?: (string | null);
    vision_model?: (string | null);
    grading_provider?: (string | null);
    grading_model?: (string | null);
    region_provider?: (string | null);
    region_model?: (string | null);
    recognition_provider?: (string | null);
    recognition_model?: (string | null);
    fallback_models?: (Array<(string)> | null);
    vision_fallback_models?: (Array<(string)> | null);
    reasoning_fallback_models?: (Array<(string)> | null);
    review_threshold?: (number | null);
    max_concurrency?: (number | null);
};

export type TeacherBatchCreate = {
    rows: Array<TeacherBatchRow>;
    dry_run?: boolean;
};

export type TeacherBatchResult = {
    created?: number;
    skipped?: number;
    rows?: Array<TeacherBatchRowResult>;
    errors?: Array<TeacherBatchRowResult>;
};

export type TeacherBatchRow = {
    name?: (string | null);
    employee_no?: (string | null);
    email?: (string | null);
    subjects?: (string | null);
    class_names?: (string | null);
};

export type TeacherBatchRowResult = {
    name?: (string | null);
    email?: (string | null);
    action: string;
    message?: (string | null);
};

export type TeachingProfilePublic = {
    class_ids?: Array<(string)>;
    class_names?: Array<(string)>;
    subjects?: Array<(string)>;
};

export type TeachingProfileUpdate = {
    class_ids?: Array<(string)>;
    subjects?: Array<(string)>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UsageReconciliationStatus = 'pending' | 'matched' | 'mismatch' | 'missing_upstream' | 'missing_local';

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    employee_no?: (string | null);
    password: string;
    org_id?: (string | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    employee_no?: (string | null);
    id: string;
    created_at?: (string | null);
    org_id?: (string | null);
    org_name?: (string | null);
};

export type UserRole = 'platform_superuser' | 'platform_admin' | 'platform_support' | 'school_owner' | 'school_admin' | 'teacher' | 'student';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
    role?: (UserRole | null);
    org_id?: (string | null);
    employee_no?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WorkflowRunStatus = 'queued' | 'running' | 'completed' | 'completed_with_errors' | 'failed';

export type ClassesReadClassesResponse = (ClassGroupsPublic);

export type ClassesCreateClassData = {
    requestBody: ClassGroupCreate;
};

export type ClassesCreateClassResponse = (ClassGroupPublic);

export type ClassesUpdateClassData = {
    classId: string;
    requestBody: ClassGroupUpdate;
};

export type ClassesUpdateClassResponse = (ClassGroupPublic);

export type ClassesDeleteClassData = {
    classId: string;
};

export type ClassesDeleteClassResponse = (Message);

export type ClassesReadStudentsData = {
    classId: string;
};

export type ClassesReadStudentsResponse = (StudentsPublic);

export type ClassesCreateStudentData = {
    classId: string;
    requestBody: StudentCreate;
};

export type ClassesCreateStudentResponse = (StudentPublic);

export type ClassesCreateStudentsBatchData = {
    classId: string;
    requestBody: StudentBatchCreate;
};

export type ClassesCreateStudentsBatchResponse = (StudentBatchResult);

export type ClassesUpdateStudentData = {
    requestBody: StudentUpdate;
    studentId: string;
};

export type ClassesUpdateStudentResponse = (StudentPublic);

export type ClassesDeleteStudentData = {
    studentId: string;
};

export type ClassesDeleteStudentResponse = (Message);

export type ClassesBindStudentAccountData = {
    requestBody: StudentBindAccount;
    studentId: string;
};

export type ClassesBindStudentAccountResponse = (StudentPublic);

export type ClassesUnbindStudentAccountData = {
    studentId: string;
};

export type ClassesUnbindStudentAccountResponse = (StudentPublic);

export type CommerceCatalogResponse = (CommerceCatalogPublic);

export type CommerceListPlansResponse = (Array<PlanVersion>);

export type CommerceCreatePlanData = {
    requestBody: PlanVersionCreate;
};

export type CommerceCreatePlanResponse = (PlanVersion);

export type CommerceListAddonsResponse = (Array<AddonSku>);

export type CommerceCreateAddonData = {
    requestBody: AddonSkuCreate;
};

export type CommerceCreateAddonResponse = (AddonSku);

export type CommerceUpdatePlanPublicationData = {
    planId: string;
    requestBody: CatalogPublicationUpdate;
};

export type CommerceUpdatePlanPublicationResponse = (PlanVersion);

export type CommerceUpdateAddonPublicationData = {
    addonId: string;
    requestBody: CatalogPublicationUpdate;
};

export type CommerceUpdateAddonPublicationResponse = (AddonSku);

export type CommerceListOrdersResponse = (Array<AdminCommerceOrderPublic>);

export type CommerceCreateOrderData = {
    requestBody: CommerceOrderCreate;
};

export type CommerceCreateOrderResponse = (CommerceOrderPublic);

export type CommerceReadOrderData = {
    orderId: string;
};

export type CommerceReadOrderResponse = (CommerceOrderPublic);

export type CommerceStartWechatPayData = {
    orderId: string;
};

export type CommerceStartWechatPayResponse = ({
    [key: string]: (string);
});

export type CommerceConfirmBankTransferData = {
    orderId: string;
    requestBody: BankTransferConfirm;
};

export type CommerceConfirmBankTransferResponse = (CommerceOrderPublic);

export type CommerceApplyInvoiceData = {
    requestBody: InvoiceApplicationCreate;
};

export type CommerceApplyInvoiceResponse = (InvoiceApplicationPublic);

export type CommerceListInvoicesResponse = (Array<InvoiceApplicationPublic>);

export type CommerceReviewInvoiceData = {
    applicationId: string;
    requestBody: InvoiceReview;
};

export type CommerceReviewInvoiceResponse = (InvoiceApplicationPublic);

export type CommerceRequestRefundData = {
    requestBody: RefundRequestCreate;
};

export type CommerceRequestRefundResponse = (RefundRequestPublic);

export type CommerceListRefundsResponse = (Array<RefundRequestPublic>);

export type CommerceReviewRefundData = {
    refundId: string;
    requestBody: RefundReview;
};

export type CommerceReviewRefundResponse = (RefundRequestPublic);

export type CommerceOrgBillingResponse = (BillingSummaryPublic);

export type CommerceWechatWebhookData = {
    wechatpayNonce: string;
    wechatpaySignature: string;
    wechatpayTimestamp: string;
};

export type CommerceWechatWebhookResponse = ({
    [key: string]: (string);
});

export type ExamsReadExamWorkflowSummaryData = {
    examId: string;
};

export type ExamsReadExamWorkflowSummaryResponse = (ExamWorkflowSummaryPublic);

export type ExamsReadExamsData = {
    limit?: number;
    skip?: number;
};

export type ExamsReadExamsResponse = (ExamsPublic);

export type ExamsCreateExamData = {
    requestBody: ExamCreate;
};

export type ExamsCreateExamResponse = (ExamPublic);

export type ExamsReadQuestionBankData = {
    difficulty?: (number | null);
    knowledgePoint?: (string | null);
    questionType?: (string | null);
};

export type ExamsReadQuestionBankResponse = (QuestionBankPublic);

export type ExamsComposeExamData = {
    requestBody: ExamComposeRequest;
};

export type ExamsComposeExamResponse = (ExamPublic);

export type ExamsReadExamData = {
    examId: string;
};

export type ExamsReadExamResponse = (ExamPublic);

export type ExamsUpdateExamData = {
    examId: string;
    requestBody: ExamUpdate;
};

export type ExamsUpdateExamResponse = (ExamPublic);

export type ExamsDeleteExamData = {
    examId: string;
};

export type ExamsDeleteExamResponse = (Message);

export type ExamsReadGradingAssignmentsData = {
    examId: string;
};

export type ExamsReadGradingAssignmentsResponse = (GradingAssignmentsPublic);

export type ExamsUpdateGradingAssignmentsData = {
    examId: string;
    requestBody: GradingAssignmentsUpdate;
};

export type ExamsUpdateGradingAssignmentsResponse = (GradingAssignmentsPublic);

export type ExamsUploadExamFileData = {
    examId: string;
    formData: Body_exams_upload_exam_file;
};

export type ExamsUploadExamFileResponse = (ExamDocumentPublic);

export type ExamsReadExamFilesData = {
    examId: string;
};

export type ExamsReadExamFilesResponse = (ExamDocumentsPublic);

export type ExamsClearExamPaperFilesData = {
    examId: string;
};

export type ExamsClearExamPaperFilesResponse = (ExamDocumentsPublic);

export type ExamsUploadExamFilesData = {
    examId: string;
    formData: Body_exams_upload_exam_files;
};

export type ExamsUploadExamFilesResponse = (ExamDocumentsPublic);

export type ExamsReorderExamFilesData = {
    examId: string;
    requestBody: ExamDocumentOrderUpdate;
};

export type ExamsReorderExamFilesResponse = (ExamDocumentsPublic);

export type ExamsDeleteExamFileData = {
    documentId: string;
    examId: string;
};

export type ExamsDeleteExamFileResponse = (ExamDocumentsPublic);

export type ExamsRecognizeExamFilesWithReferenceAlgorithmData = {
    examId: string;
    requestBody: ExamDocumentRecognitionRequest;
};

export type ExamsRecognizeExamFilesWithReferenceAlgorithmResponse = ({
    [key: string]: unknown;
});

export type ExamsReadExamFileContentData = {
    authorization?: (string | null);
    documentId: string;
    examId: string;
};

export type ExamsReadExamFileContentResponse = (unknown);

export type ExamsReadExamFileSourceImageData = {
    documentId: string;
    examId: string;
};

export type ExamsReadExamFileSourceImageResponse = (unknown);

export type ExamsReadExamFilePageImageData = {
    authorization?: (string | null);
    documentId: string;
    examId: string;
    pageNumber: number;
};

export type ExamsReadExamFilePageImageResponse = (unknown);

export type ExamsReadExamFilePreprocessingPreviewData = {
    authorization?: (string | null);
    documentId: string;
    examId: string;
    kind: 'detected_overlay' | 'corrected_spread';
};

export type ExamsReadExamFilePreprocessingPreviewResponse = (unknown);

export type ExamsPreviewExamFileWithQuadsData = {
    documentId: string;
    examId: string;
    requestBody: ExamDocumentQuadPreprocessRequest;
};

export type ExamsPreviewExamFileWithQuadsResponse = ({
    [key: string]: unknown;
});

export type ExamsPreprocessExamFileWithQuadsData = {
    documentId: string;
    examId: string;
    requestBody: ExamDocumentQuadPreprocessRequest;
};

export type ExamsPreprocessExamFileWithQuadsResponse = (ExamDocumentPublic);

export type ExamsAutoRectifyExamFileData = {
    documentId: string;
    examId: string;
};

export type ExamsAutoRectifyExamFileResponse = (ExamDocumentPublic);

export type ExamsAutoRectifyExamFilesData = {
    examId: string;
};

export type ExamsAutoRectifyExamFilesResponse = (ExamDocumentsPublic);

export type ExamsReadExamRegionCandidatesData = {
    documentId: string;
    engine?: 'layout_projection_v0' | 'layout_ocr_anchor_v1' | 'gemini_layout_v1';
    examId: string;
    pageNumber?: number;
};

export type ExamsReadExamRegionCandidatesResponse = (ExamRegionCandidatesPublic);

export type ExamsRecognizeExamDocumentWithReferenceAlgorithmData = {
    documentId: string;
    examId: string;
};

export type ExamsRecognizeExamDocumentWithReferenceAlgorithmResponse = ({
    [key: string]: unknown;
});

export type ExamsRecognizeExamDocumentPageWithReferenceAlgorithmData = {
    documentId: string;
    examId: string;
    pageNumber: number;
};

export type ExamsRecognizeExamDocumentPageWithReferenceAlgorithmResponse = ({
    [key: string]: unknown;
});

export type ExamsUploadStudentSubmissionData = {
    examId: string;
    formData: Body_exams_upload_student_submission;
};

export type ExamsUploadStudentSubmissionResponse = (StudentSubmissionPublic);

export type ExamsReadStudentSubmissionsData = {
    examId: string;
};

export type ExamsReadStudentSubmissionsResponse = (StudentSubmissionsPublic);

export type ExamsReadExamScoresSummaryData = {
    examId: string;
};

export type ExamsReadExamScoresSummaryResponse = (ExamScoreSummaryPublic);

export type ExamsCreateExamAnalysisReportData = {
    examId: string;
};

export type ExamsCreateExamAnalysisReportResponse = (ExamAnalysisReportPublic);

export type ExamsPreprocessStudentSubmissionPhotoData = {
    examId: string;
    formData: Body_exams_preprocess_student_submission_photo;
};

export type ExamsPreprocessStudentSubmissionPhotoResponse = (StudentSubmissionPublic);

export type ExamsAppendStudentSubmissionPagesData = {
    examId: string;
    formData: Body_exams_append_student_submission_pages;
    submissionId: string;
};

export type ExamsAppendStudentSubmissionPagesResponse = (StudentSubmissionPublic);

export type ExamsReadStudentSubmissionData = {
    examId: string;
    submissionId: string;
};

export type ExamsReadStudentSubmissionResponse = (StudentSubmissionPublic);

export type ExamsUpdateStudentSubmissionRegistrationData = {
    examId: string;
    requestBody: StudentSubmissionRegistrationUpdate;
    submissionId: string;
};

export type ExamsUpdateStudentSubmissionRegistrationResponse = (StudentSubmissionPublic);

export type ExamsCreateStudentSubmissionProcessingTaskData = {
    examId: string;
    submissionId: string;
};

export type ExamsCreateStudentSubmissionProcessingTaskResponse = (ProcessingTaskPublic);

export type ExamsReadStudentSubmissionPageImageData = {
    authorization?: (string | null);
    examId: string;
    pageNumber: number;
    submissionId: string;
};

export type ExamsReadStudentSubmissionPageImageResponse = (unknown);

export type ExamsReadStudentSubmissionTemplateRegionsData = {
    examId: string;
    pageNumber?: (number | null);
    submissionId: string;
};

export type ExamsReadStudentSubmissionTemplateRegionsResponse = (ExamRegionsPublic);

export type ExamsReadStudentSubmissionRegionCropData = {
    authorization?: (string | null);
    examId: string;
    regionId: string;
    submissionId: string;
};

export type ExamsReadStudentSubmissionRegionCropResponse = (unknown);

export type ExamsReadSubmissionAnnotationCropData = {
    annotationId: string;
    authorization?: (string | null);
    examId: string;
    submissionId: string;
};

export type ExamsReadSubmissionAnnotationCropResponse = (unknown);

export type ExamsReadSubmissionAnnotationsData = {
    examId: string;
    submissionId: string;
};

export type ExamsReadSubmissionAnnotationsResponse = (SubmissionAnnotationsPublic);

export type ExamsCreateSubmissionAnnotationData = {
    examId: string;
    requestBody: SubmissionAnnotationCreate;
    submissionId: string;
};

export type ExamsCreateSubmissionAnnotationResponse = (SubmissionAnnotationPublic);

export type ExamsUpdateSubmissionAnnotationData = {
    annotationId: string;
    examId: string;
    requestBody: SubmissionAnnotationUpdate;
    submissionId: string;
};

export type ExamsUpdateSubmissionAnnotationResponse = (SubmissionAnnotationPublic);

export type ExamsDeleteSubmissionAnnotationData = {
    annotationId: string;
    examId: string;
    submissionId: string;
};

export type ExamsDeleteSubmissionAnnotationResponse = (Message);

export type ExamsReadStandardAnswersData = {
    examId: string;
};

export type ExamsReadStandardAnswersResponse = (StandardAnswersPublic);

export type ExamsCreateStandardAnswerData = {
    examId: string;
    requestBody: StandardAnswerCreate;
};

export type ExamsCreateStandardAnswerResponse = (StandardAnswerPublic);

export type ExamsReadStandardAnswerData = {
    answerId: string;
    examId: string;
};

export type ExamsReadStandardAnswerResponse = (StandardAnswerPublic);

export type ExamsUpdateStandardAnswerData = {
    answerId: string;
    examId: string;
    requestBody: StandardAnswerUpdate;
};

export type ExamsUpdateStandardAnswerResponse = (StandardAnswerPublic);

export type ExamsDeleteStandardAnswerData = {
    answerId: string;
    examId: string;
};

export type ExamsDeleteStandardAnswerResponse = (Message);

export type ExamsReadExamRegionsData = {
    examId: string;
};

export type ExamsReadExamRegionsResponse = (ExamRegionsPublic);

export type ExamsCreateExamRegionData = {
    examId: string;
    requestBody: ExamRegionCreate;
};

export type ExamsCreateExamRegionResponse = (ExamRegionPublic);

export type ExamsUpdateExamRegionData = {
    examId: string;
    regionId: string;
    requestBody: ExamRegionUpdate;
};

export type ExamsUpdateExamRegionResponse = (ExamRegionPublic);

export type ExamsDeleteExamRegionData = {
    examId: string;
    regionId: string;
};

export type ExamsDeleteExamRegionResponse = (Message);

export type FilesUploadFileData = {
    formData: Body_files_upload_file;
};

export type FilesUploadFileResponse = (StoredFilePublic);

export type GradingCreateRecognitionRunData = {
    requestBody: RecognitionRunCreate;
};

export type GradingCreateRecognitionRunResponse = (GradingRunPublic);

export type GradingReadRecognitionItemsData = {
    runId: string;
};

export type GradingReadRecognitionItemsResponse = (Array<RecognitionItemPublic>);

export type GradingUpdateRecognitionItemData = {
    itemId: string;
    requestBody: RecognitionItemUpdate;
};

export type GradingUpdateRecognitionItemResponse = (RecognitionItemPublic);

export type GradingConfirmRecognitionData = {
    runId: string;
};

export type GradingConfirmRecognitionResponse = (GradingRunPublic);

export type GradingCreateRunData = {
    requestBody: GradingRunCreate;
};

export type GradingCreateRunResponse = (GradingRunPublic);

export type GradingListRunsData = {
    examId: string;
};

export type GradingListRunsResponse = (GradingRunsPublic);

export type GradingGetRunData = {
    runId: string;
};

export type GradingGetRunResponse = (GradingRunPublic);

export type GradingStartRunData = {
    runId: string;
};

export type GradingStartRunResponse = (GradingRunPublic);

export type GradingRetryRunData = {
    runId: string;
};

export type GradingRetryRunResponse = (GradingRunPublic);

export type GradingGenerateRubricsData = {
    examId: string;
};

export type GradingGenerateRubricsResponse = (ProcessingTaskPublic);

export type GradingPublishAnswersData = {
    runId: string;
};

export type GradingPublishAnswersResponse = (GradingRunPublic);

export type GradingReviewQueueData = {
    runId: string;
};

export type GradingReviewQueueResponse = (Array<GradingReviewItem>);

export type GradingAuditLogData = {
    runId: string;
};

export type GradingAuditLogResponse = (Array<GradingAuditEventPublic>);

export type GradingPublishExamScoresData = {
    examId: string;
    requestBody: ScoreReleaseCreate;
};

export type GradingPublishExamScoresResponse = (ScoreReleasePublic);

export type GradingGetCurrentScoreReleaseData = {
    examId: string;
};

export type GradingGetCurrentScoreReleaseResponse = ((ScoreReleasePublic | null));

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type ModelOfferingsListModelOfferingsResponse = (PlatformModelOfferingsPublic);

export type ModelOfferingsCreateModelOfferingData = {
    requestBody: PlatformModelOfferingCreate;
};

export type ModelOfferingsCreateModelOfferingResponse = (PlatformModelOfferingPublic);

export type ModelOfferingsUpdateModelOfferingData = {
    offeringId: string;
    requestBody: PlatformModelOfferingUpdate;
};

export type ModelOfferingsUpdateModelOfferingResponse = (PlatformModelOfferingPublic);

export type ModelOfferingsListOfferingRatesData = {
    offeringId: string;
};

export type ModelOfferingsListOfferingRatesResponse = (Array<OfferingRateVersionPublic>);

export type ModelOfferingsCreateOfferingRateData = {
    offeringId: string;
    requestBody: OfferingRateVersionCreate;
};

export type ModelOfferingsCreateOfferingRateResponse = (OfferingRateVersionPublic);

export type OrgReadOrgSettingsResponse = (OrgSettingsPublic);

export type OrgUpdateOrgSettingsData = {
    requestBody: OrgSettingsUpdate;
};

export type OrgUpdateOrgSettingsResponse = (OrgSettingsPublic);

export type OrgReadOrgOnboardingResponse = (OrgOnboardingPublic);

export type OrgReadOrgModelSettingsResponse = (SchoolModelSettingsPublic);

export type OrgUpdateOrgModelSettingData = {
    requestBody: SchoolModelSelectionUpdate;
    scope: SchoolModelScope;
};

export type OrgUpdateOrgModelSettingResponse = (SchoolModelSettingsPublic);

export type OrgReadBillingEntitlementResponse = (BillingEntitlementPublic);

export type OrgReadBillingSummaryResponse = (BillingSummaryPublic);

export type OrgReadBillingUsageData = {
    limit?: number;
    offset?: number;
};

export type OrgReadBillingUsageResponse = (BillingUsagePublic);

export type OrgReadBillingLedgerData = {
    limit?: number;
    offset?: number;
};

export type OrgReadBillingLedgerResponse = (CreditLedgerPublic);

export type PlatformReadModelUsageOverviewData = {
    days?: number;
    orgId?: (string | null);
};

export type PlatformReadModelUsageOverviewResponse = (PlatformModelUsageOverviewPublic);

export type PlatformListModelUsageEventsData = {
    days?: number;
    limit?: number;
    offset?: number;
    orgId?: (string | null);
    purpose?: (string | null);
    status?: (ModelUsageStatus | null);
};

export type PlatformListModelUsageEventsResponse = (PlatformModelUsageEventsPublic);

export type PlatformReadPlatformDirectoryData = {
    category?: string;
    classId?: (string | null);
    limit?: number;
    offset?: number;
    orgId?: (string | null);
    q?: (string | null);
};

export type PlatformReadPlatformDirectoryResponse = (PlatformDirectoryPublic);

export type PlatformListOrgsResponse = (PlatformOrgsPublic);

export type PlatformCreateOrgData = {
    requestBody: PlatformOrgCreate;
};

export type PlatformCreateOrgResponse = (PlatformOrgDetail);

export type PlatformReadOrgData = {
    orgId: string;
};

export type PlatformReadOrgResponse = (PlatformOrgDetail);

export type PlatformUpdateOrgData = {
    orgId: string;
    requestBody: PlatformOrgUpdate;
};

export type PlatformUpdateOrgResponse = (PlatformOrgDetail);

export type PlatformAddOrgOwnerData = {
    orgId: string;
    requestBody: PlatformOrgOwnerCreate;
};

export type PlatformAddOrgOwnerResponse = (PlatformOrgUserItem);

export type PlatformReadSystemConfigResponse = (SystemConfigPublic);

export type PlatformUpdateSystemConfigData = {
    requestBody: SystemConfigUpdate;
};

export type PlatformUpdateSystemConfigResponse = (SystemConfigPublic);

export type PlatformListBillingRatesResponse = (Array<BillingRateVersion>);

export type PlatformCreateBillingRateData = {
    requestBody: BillingRateVersionCreate;
};

export type PlatformCreateBillingRateResponse = (BillingRateVersion);

export type PlatformUpsertOrgSubscriptionData = {
    orgId: string;
    requestBody: SubscriptionUpsert;
};

export type PlatformUpsertOrgSubscriptionResponse = (BillingSummaryPublic);

export type PlatformGrantOrgCreditsData = {
    orgId: string;
    requestBody: CreditGrantCreate;
};

export type PlatformGrantOrgCreditsResponse = (BillingSummaryPublic);

export type PlatformGrantOrgAnswerQuotaData = {
    orgId: string;
    requestBody: AnswerQuotaGrantCreate;
};

export type PlatformGrantOrgAnswerQuotaResponse = (BillingSummaryPublic);

export type PlatformReadOrgBillingData = {
    orgId: string;
};

export type PlatformReadOrgBillingResponse = (BillingSummaryPublic);

export type PlatformReadOrgBillingLedgerData = {
    limit?: number;
    offset?: number;
    orgId: string;
};

export type PlatformReadOrgBillingLedgerResponse = (CreditLedgerPublic);

export type PlatformReadOrgUsagePolicyData = {
    orgId: string;
};

export type PlatformReadOrgUsagePolicyResponse = (OrganizationUsagePolicyPublic);

export type PlatformUpdateOrgUsagePolicyData = {
    orgId: string;
    requestBody: OrganizationUsagePolicyUpdate;
};

export type PlatformUpdateOrgUsagePolicyResponse = (OrganizationUsagePolicyPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProviderChannelsListChannelsResponse = (ProviderChannelsPublic);

export type ProviderChannelsCreateChannelData = {
    requestBody: ProviderChannelCreate;
};

export type ProviderChannelsCreateChannelResponse = (ProviderChannelPublic);

export type ProviderChannelsImportEnvironmentChannelsResponse = (ProviderChannelsPublic);

export type ProviderChannelsUpdateChannelData = {
    channelId: string;
    requestBody: ProviderChannelUpdate;
};

export type ProviderChannelsUpdateChannelResponse = (ProviderChannelPublic);

export type ProviderChannelsRotateCredentialData = {
    channelId: string;
    requestBody: ProviderCredentialUpdate;
};

export type ProviderChannelsRotateCredentialResponse = (ProviderChannelPublic);

export type ProviderChannelsRotateBillingCredentialData = {
    channelId: string;
    requestBody: ProviderBillingCredentialUpdate;
};

export type ProviderChannelsRotateBillingCredentialResponse = (ProviderChannelPublic);

export type ProviderChannelsListModelMappingsData = {
    channelId: string;
};

export type ProviderChannelsListModelMappingsResponse = (Array<ProviderModelMappingPublic>);

export type ProviderChannelsCreateModelMappingData = {
    channelId: string;
    requestBody: ProviderModelMappingCreate;
};

export type ProviderChannelsCreateModelMappingResponse = (ProviderModelMappingPublic);

export type ProviderChannelsDiscoverUpstreamModelsData = {
    channelId: string;
};

export type ProviderChannelsDiscoverUpstreamModelsResponse = (ProviderModelDiscoveryResult);

export type ProviderChannelsUpdateModelMappingData = {
    channelId: string;
    mappingId: string;
    requestBody: ProviderModelMappingUpdate;
};

export type ProviderChannelsUpdateModelMappingResponse = (ProviderModelMappingPublic);

export type ProviderChannelsListRoutePoliciesData = {
    purpose?: (string | null);
};

export type ProviderChannelsListRoutePoliciesResponse = (Array<ModelRoutePolicyPublic>);

export type ProviderChannelsListFunctionModelDefaultsResponse = (Array<FunctionModelAssignmentPublic>);

export type ProviderChannelsUpdateFunctionModelDefaultData = {
    purpose: string;
    requestBody: FunctionModelAssignmentUpdate;
};

export type ProviderChannelsUpdateFunctionModelDefaultResponse = (FunctionModelAssignmentPublic);

export type ProviderChannelsAddRouteTargetData = {
    canonicalModel: string;
    purpose: string;
    requestBody: ModelRouteTargetInput;
};

export type ProviderChannelsAddRouteTargetResponse = (ModelRoutePolicyPublic);

export type ProviderChannelsReadRoutePolicyData = {
    canonicalModel?: (string | null);
    purpose: string;
};

export type ProviderChannelsReadRoutePolicyResponse = (ModelRoutePolicyPublic);

export type ProviderChannelsUpsertRoutePolicyData = {
    purpose: string;
    requestBody: ModelRoutePolicyUpsert;
};

export type ProviderChannelsUpsertRoutePolicyResponse = (ModelRoutePolicyPublic);

export type ProviderChannelsListRouteVersionsData = {
    canonicalModel: string;
    purpose: string;
};

export type ProviderChannelsListRouteVersionsResponse = (Array<ModelRouteVersionPublic>);

export type ProviderChannelsPublishRouteVersionData = {
    purpose: string;
    versionId: string;
};

export type ProviderChannelsPublishRouteVersionResponse = (ModelRouteVersionPublic);

export type ProviderChannelsListInternalRatesData = {
    channelId: string;
};

export type ProviderChannelsListInternalRatesResponse = (Array<ProviderInternalRateVersionPublic>);

export type ProviderChannelsCreateInternalRateData = {
    channelId: string;
    requestBody: ProviderInternalRateVersionCreate;
};

export type ProviderChannelsCreateInternalRateResponse = (ProviderInternalRateVersionPublic);

export type ProviderChannelsTestChannelData = {
    channelId: string;
    requestBody: ProviderChannelTestRequest;
};

export type ProviderChannelsTestChannelResponse = (ProviderChannelTestResult);

export type ProviderChannelsResetChannelHealthData = {
    channelId: string;
};

export type ProviderChannelsResetChannelHealthResponse = (ProviderChannelPublic);

export type ProviderChannelsListReconciliationsData = {
    channelId: string;
};

export type ProviderChannelsListReconciliationsResponse = (Array<ReconciliationBatchPublic>);

export type ProviderChannelsImportReconciliationData = {
    channelId: string;
    requestBody: ReconciliationImport;
};

export type ProviderChannelsImportReconciliationResponse = (ReconciliationBatchPublic);

export type ProviderChannelsSyncNewApiReconciliationData = {
    channelId: string;
};

export type ProviderChannelsSyncNewApiReconciliationResponse = (NewApiBillingSyncPublic);

export type QuestionAnswerWorkflowListExamQuestionsData = {
    examId: string;
};

export type QuestionAnswerWorkflowListExamQuestionsResponse = (ExamQuestionsPublic);

export type QuestionAnswerWorkflowCreateQuestionRecognitionRunData = {
    examId: string;
    requestBody: QuestionRecognitionRunCreate;
};

export type QuestionAnswerWorkflowCreateQuestionRecognitionRunResponse = (QuestionRecognitionRunPublic);

export type QuestionAnswerWorkflowListQuestionRecognitionRunsData = {
    examId: string;
};

export type QuestionAnswerWorkflowListQuestionRecognitionRunsResponse = (QuestionRecognitionRunsPublic);

export type QuestionAnswerWorkflowImportMarkingRecognitionRunData = {
    examId: string;
    requestBody: MarkingRecognitionImport;
};

export type QuestionAnswerWorkflowImportMarkingRecognitionRunResponse = (QuestionRecognitionRunPublic);

export type QuestionAnswerWorkflowGetQuestionRecognitionRunData = {
    examId: string;
    runId: string;
};

export type QuestionAnswerWorkflowGetQuestionRecognitionRunResponse = (QuestionRecognitionRunPublic);

export type QuestionAnswerWorkflowListQuestionRecognitionItemsData = {
    examId: string;
    runId: string;
};

export type QuestionAnswerWorkflowListQuestionRecognitionItemsResponse = (Array<QuestionRecognitionItemPublic>);

export type QuestionAnswerWorkflowUpdateQuestionRecognitionItemData = {
    examId: string;
    itemId: string;
    requestBody: QuestionRecognitionItemUpdate;
};

export type QuestionAnswerWorkflowUpdateQuestionRecognitionItemResponse = (QuestionRecognitionItemPublic);

export type QuestionAnswerWorkflowConfirmQuestionRecognitionRunData = {
    examId: string;
    runId: string;
};

export type QuestionAnswerWorkflowConfirmQuestionRecognitionRunResponse = (QuestionRecognitionRunPublic);

export type QuestionAnswerWorkflowCreateAnswerPreparationRunData = {
    examId: string;
    requestBody: AnswerPreparationRunCreate;
};

export type QuestionAnswerWorkflowCreateAnswerPreparationRunResponse = (AnswerPreparationRunPublic);

export type QuestionAnswerWorkflowListAnswerPreparationRunsData = {
    examId: string;
};

export type QuestionAnswerWorkflowListAnswerPreparationRunsResponse = (AnswerPreparationRunsPublic);

export type QuestionAnswerWorkflowGetAnswerPreparationRunData = {
    examId: string;
    runId: string;
};

export type QuestionAnswerWorkflowGetAnswerPreparationRunResponse = (AnswerPreparationRunPublic);

export type QuestionAnswerWorkflowListAnswerPreparationItemsData = {
    examId: string;
    runId: string;
};

export type QuestionAnswerWorkflowListAnswerPreparationItemsResponse = (Array<AnswerPreparationItemPublic>);

export type QuestionAnswerWorkflowUpdateAnswerPreparationItemData = {
    examId: string;
    itemId: string;
    requestBody: AnswerPreparationItemUpdate;
};

export type QuestionAnswerWorkflowUpdateAnswerPreparationItemResponse = (AnswerPreparationItemPublic);

export type QuestionAnswerWorkflowConfirmAnswerPreparationRunData = {
    examId: string;
    runId: string;
};

export type QuestionAnswerWorkflowConfirmAnswerPreparationRunResponse = (AnswerPreparationRunPublic);

export type QuestionAnswerWorkflowListStandardAnswerRevisionsData = {
    examId: string;
};

export type QuestionAnswerWorkflowListStandardAnswerRevisionsResponse = (StandardAnswerRevisionsPublic);

export type QuestionAnswerWorkflowPublishStandardAnswerRevisionsData = {
    examId: string;
    requestBody: StandardAnswerPublishRequest;
};

export type QuestionAnswerWorkflowPublishStandardAnswerRevisionsResponse = (StandardAnswerRevisionsPublic);

export type StudentsReadMyExamsResponse = (StudentExamListPublic);

export type StudentsReadMyExamReportData = {
    examId: string;
};

export type StudentsReadMyExamReportResponse = (StudentExamReportPublic);

export type TasksCreateTestTaskData = {
    requestBody: ProcessingTaskCreate;
};

export type TasksCreateTestTaskResponse = (ProcessingTaskPublic);

export type TasksReadTaskData = {
    taskId: string;
};

export type TasksReadTaskResponse = (ProcessingTaskPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersCreateTeachersBatchData = {
    requestBody: TeacherBatchCreate;
};

export type UsersCreateTeachersBatchResponse = (TeacherBatchResult);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterOrganizationData = {
    requestBody: OrganizationSignupCreate;
};

export type UsersRegisterOrganizationResponse = (OrganizationSignupRequested);

export type UsersResendOrganizationSignupData = {
    requestBody: OrganizationSignupResend;
};

export type UsersResendOrganizationSignupResponse = (OrganizationSignupRequested);

export type UsersVerifyOrganizationSignupData = {
    requestBody: OrganizationSignupVerify;
};

export type UsersVerifyOrganizationSignupResponse = (OrganizationSignupCompleted);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UsersReadTeachingProfileData = {
    userId: string;
};

export type UsersReadTeachingProfileResponse = (TeachingProfilePublic);

export type UsersUpdateTeachingProfileData = {
    requestBody: TeachingProfileUpdate;
    userId: string;
};

export type UsersUpdateTeachingProfileResponse = (TeachingProfilePublic);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = ({
    [key: string]: unknown;
});

export type UtilsHealthResponse = ({
    [key: string]: (string);
});

export type UtilsLivenessResponse = ({
    [key: string]: (string);
});

export type UtilsReadinessResponse = ({
    [key: string]: unknown;
});