server {
    listen 80;
    server_name app.dianfandig.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 503;
    }
}
