"""add dynamic provider routing

Revision ID: 24301a6c50ac
Revises: c2e4f6a8b0d1
Create Date: 2026-07-25 22:25:47.441756

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "24301a6c50ac"
down_revision = "c2e4f6a8b0d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modelroutepolicy",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "purpose", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "canonical_model",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "sticky_scope", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("purpose", name="uq_route_purpose"),
    )
    op.create_index(
        op.f("ix_modelroutepolicy_canonical_model"),
        "modelroutepolicy",
        ["canonical_model"],
        unique=False,
    )
    op.create_index(
        op.f("ix_modelroutepolicy_purpose"),
        "modelroutepolicy",
        ["purpose"],
        unique=False,
    )
    op.create_table(
        "providerchannel",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "display_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "official_api",
                "authorized_relay",
                "new_api",
                "sub2api",
                "cli_proxy_api",
                "custom",
                name="providerchannelkind",
            ),
            nullable=False,
        ),
        sa.Column(
            "protocol",
            sa.Enum("openai_chat", "openai_responses", name="providerprotocol"),
            nullable=False,
        ),
        sa.Column(
            "base_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("risk_acknowledged", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("max_concurrency", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_providerchannel_code"), "providerchannel", ["code"], unique=True
    )
    op.create_table(
        "providerauditlog",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "action", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["providerchannel.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_providerauditlog_action"), "providerauditlog", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_providerauditlog_channel_id"),
        "providerauditlog",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_providerauditlog_created_at"),
        "providerauditlog",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "providercredential",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("ciphertext", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "nonce", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column(
            "fingerprint", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "last_four", sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False
        ),
        sa.Column("rotated_by_id", sa.Uuid(), nullable=True),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["providerchannel.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["rotated_by_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_providercredential_channel_id"),
        "providercredential",
        ["channel_id"],
        unique=True,
    )
    op.create_table(
        "providerhealthstate",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column(
            "canonical_model",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "unknown",
                "healthy",
                "degraded",
                "open",
                "disabled",
                name="providerhealthstatus",
            ),
            nullable=False,
        ),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("consecutive_missing_usage", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("latency_ewma_ms", sa.Float(), nullable=True),
        sa.Column("circuit_open_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_http_status", sa.Integer(), nullable=True),
        sa.Column(
            "last_error_code",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["providerchannel.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "channel_id", "canonical_model", name="uq_health_channel_model"
        ),
    )
    op.create_index(
        op.f("ix_providerhealthstate_canonical_model"),
        "providerhealthstate",
        ["canonical_model"],
        unique=False,
    )
    op.create_index(
        op.f("ix_providerhealthstate_channel_id"),
        "providerhealthstate",
        ["channel_id"],
        unique=False,
    )
    op.create_table(
        "providerinternalrateversion",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column(
            "canonical_model",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=False,
        ),
        sa.Column(
            "version", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_micrormb_per_million", sa.BigInteger(), nullable=False),
        sa.Column("output_micrormb_per_million", sa.BigInteger(), nullable=False),
        sa.Column("image_micrormb_per_million", sa.BigInteger(), nullable=False),
        sa.Column("cached_input_micrormb_per_million", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["providerchannel.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "channel_id", "canonical_model", "version", name="uq_provider_rate_version"
        ),
    )
    op.create_index(
        op.f("ix_providerinternalrateversion_canonical_model"),
        "providerinternalrateversion",
        ["canonical_model"],
        unique=False,
    )
    op.create_index(
        op.f("ix_providerinternalrateversion_channel_id"),
        "providerinternalrateversion",
        ["channel_id"],
        unique=False,
    )
    op.create_table(
        "providermodelmapping",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column(
            "canonical_model",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=False,
        ),
        sa.Column(
            "upstream_model",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=False,
        ),
        sa.Column("supports_vision", sa.Boolean(), nullable=False),
        sa.Column("supports_structured_output", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["providerchannel.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "channel_id", "canonical_model", name="uq_provider_channel_model"
        ),
    )
    op.create_index(
        op.f("ix_providermodelmapping_canonical_model"),
        "providermodelmapping",
        ["canonical_model"],
        unique=False,
    )
    op.create_index(
        op.f("ix_providermodelmapping_channel_id"),
        "providermodelmapping",
        ["channel_id"],
        unique=False,
    )
    op.create_table(
        "modelroutetarget",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("mapping_id", sa.Uuid(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mapping_id"], ["providermodelmapping.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"], ["modelroutepolicy.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_id", "mapping_id", name="uq_route_policy_mapping"),
    )
    op.create_index(
        op.f("ix_modelroutetarget_mapping_id"),
        "modelroutetarget",
        ["mapping_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_modelroutetarget_policy_id"),
        "modelroutetarget",
        ["policy_id"],
        unique=False,
    )
    op.add_column("modelusageevent", sa.Column("channel_id", sa.Uuid(), nullable=True))
    op.add_column(
        "modelusageevent", sa.Column("route_policy_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "modelusageevent",
        sa.Column(
            "upstream_request_id",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "modelusageevent", sa.Column("http_status", sa.Integer(), nullable=True)
    )
    op.add_column(
        "modelusageevent",
        sa.Column(
            "cached_input_tokens", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "modelusageevent",
        sa.Column("reasoning_tokens", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "modelusageevent",
        sa.Column("internal_rate_version_id", sa.Uuid(), nullable=True),
    )
    op.create_index(
        op.f("ix_modelusageevent_channel_id"),
        "modelusageevent",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_modelusageevent_route_policy_id"),
        "modelusageevent",
        ["route_policy_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_modelusageevent_route_policy",
        "modelusageevent",
        "modelroutepolicy",
        ["route_policy_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_modelusageevent_internal_rate",
        "modelusageevent",
        "providerinternalrateversion",
        ["internal_rate_version_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_modelusageevent_channel",
        "modelusageevent",
        "providerchannel",
        ["channel_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_modelusageevent_channel", "modelusageevent", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_modelusageevent_internal_rate", "modelusageevent", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_modelusageevent_route_policy", "modelusageevent", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_modelusageevent_route_policy_id"), table_name="modelusageevent"
    )
    op.drop_index(op.f("ix_modelusageevent_channel_id"), table_name="modelusageevent")
    op.drop_column("modelusageevent", "internal_rate_version_id")
    op.drop_column("modelusageevent", "reasoning_tokens")
    op.drop_column("modelusageevent", "cached_input_tokens")
    op.drop_column("modelusageevent", "http_status")
    op.drop_column("modelusageevent", "upstream_request_id")
    op.drop_column("modelusageevent", "route_policy_id")
    op.drop_column("modelusageevent", "channel_id")
    op.drop_index(op.f("ix_modelroutetarget_policy_id"), table_name="modelroutetarget")
    op.drop_index(op.f("ix_modelroutetarget_mapping_id"), table_name="modelroutetarget")
    op.drop_table("modelroutetarget")
    op.drop_index(
        op.f("ix_providermodelmapping_channel_id"), table_name="providermodelmapping"
    )
    op.drop_index(
        op.f("ix_providermodelmapping_canonical_model"),
        table_name="providermodelmapping",
    )
    op.drop_table("providermodelmapping")
    op.drop_index(
        op.f("ix_providerinternalrateversion_channel_id"),
        table_name="providerinternalrateversion",
    )
    op.drop_index(
        op.f("ix_providerinternalrateversion_canonical_model"),
        table_name="providerinternalrateversion",
    )
    op.drop_table("providerinternalrateversion")
    op.drop_index(
        op.f("ix_providerhealthstate_channel_id"), table_name="providerhealthstate"
    )
    op.drop_index(
        op.f("ix_providerhealthstate_canonical_model"), table_name="providerhealthstate"
    )
    op.drop_table("providerhealthstate")
    op.drop_index(
        op.f("ix_providercredential_channel_id"), table_name="providercredential"
    )
    op.drop_table("providercredential")
    op.drop_index(op.f("ix_providerauditlog_created_at"), table_name="providerauditlog")
    op.drop_index(op.f("ix_providerauditlog_channel_id"), table_name="providerauditlog")
    op.drop_index(op.f("ix_providerauditlog_action"), table_name="providerauditlog")
    op.drop_table("providerauditlog")
    op.drop_index(op.f("ix_providerchannel_code"), table_name="providerchannel")
    op.drop_table("providerchannel")
    op.drop_index(op.f("ix_modelroutepolicy_purpose"), table_name="modelroutepolicy")
    op.drop_index(
        op.f("ix_modelroutepolicy_canonical_model"), table_name="modelroutepolicy"
    )
    op.drop_table("modelroutepolicy")
    sa.Enum(name="providerhealthstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="providerprotocol").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="providerchannelkind").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
