/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as SignupVerifyRouteImport } from './routes/signup_.verify'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPlatformRouteImport } from './routes/_layout/platform'
import { Route as LayoutOrgSettingsRouteImport } from './routes/_layout/org-settings'
import { Route as LayoutGettingStartedRouteImport } from './routes/_layout/getting-started'
import { Route as LayoutExamsRouteImport } from './routes/_layout/exams'
import { Route as LayoutComposeRouteImport } from './routes/_layout/compose'
import { Route as LayoutClassesRouteImport } from './routes/_layout/classes'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutPlatformUsageRouteImport } from './routes/_layout/platform_.usage'
import { Route as LayoutPlatformSettingsRouteImport } from './routes/_layout/platform_.settings'
import { Route as LayoutPlatformRoutingRouteImport } from './routes/_layout/platform_.routing'
import { Route as LayoutPlatformCommerceRouteImport } from './routes/_layout/platform_.commerce'
import { Route as LayoutPlatformOrgIdRouteImport } from './routes/_layout/platform_.$orgId'
import { Route as LayoutMyExamsRouteImport } from './routes/_layout/my.exams'
import { Route as LayoutExamsExamIdRouteImport } from './routes/_layout/exams_.$examId'
import { Route as LayoutExamsExamIdIndexRouteImport } from './routes/_layout/exams_.$examId.index'
import { Route as LayoutMyExamsExamIdRouteImport } from './routes/_layout/my.exams_.$examId'
import { Route as LayoutExamsExamIdWorkbenchRouteImport } from './routes/_layout/exams_.$examId.workbench'
import { Route as LayoutExamsExamIdScoresRouteImport } from './routes/_layout/exams_.$examId.scores'
import { Route as LayoutExamsExamIdReportRouteImport } from './routes/_layout/exams_.$examId.report'
import { Route as LayoutExamsExamIdQuestionsRouteImport } from './routes/_layout/exams_.$examId.questions'
import { Route as LayoutExamsExamIdMarkingRouteImport } from './routes/_layout/exams_.$examId.marking'
import { Route as LayoutExamsExamIdGradingRouteImport } from './routes/_layout/exams_.$examId.grading'
import { Route as LayoutExamsExamIdAnswersRouteImport } from './routes/_layout/exams_.$examId.answers'
import { Route as LayoutExamsExamIdSubmissionsSubmissionIdReviewRouteImport } from './routes/_layout/exams_.$examId.submissions.$submissionId.review'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const SignupVerifyRoute = SignupVerifyRouteImport.update({
  id: '/signup_/verify',
  path: '/signup/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlatformRoute = LayoutPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrgSettingsRoute = LayoutOrgSettingsRouteImport.update({
  id: '/org-settings',
  path: '/org-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGettingStartedRoute = LayoutGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExamsRoute = LayoutExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutComposeRoute = LayoutComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClassesRoute = LayoutClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlatformUsageRoute = LayoutPlatformUsageRouteImport.update({
  id: '/platform_/usage',
  path: '/platform/usage',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlatformSettingsRoute = LayoutPlatformSettingsRouteImport.update({
  id: '/platform_/settings',
  path: '/platform/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlatformRoutingRoute = LayoutPlatformRoutingRouteImport.update({
  id: '/platform_/routing',
  path: '/platform/routing',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlatformCommerceRoute = LayoutPlatformCommerceRouteImport.update({
  id: '/platform_/commerce',
  path: '/platform/commerce',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlatformOrgIdRoute = LayoutPlatformOrgIdRouteImport.update({
  id: '/platform_/$orgId',
  path: '/platform/$orgId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMyExamsRoute = LayoutMyExamsRouteImport.update({
  id: '/my/exams',
  path: '/my/exams',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExamsExamIdRoute = LayoutExamsExamIdRouteImport.update({
  id: '/exams_/$examId',
  path: '/exams/$examId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExamsExamIdIndexRoute = LayoutExamsExamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutExamsExamIdRoute,
} as any)
const LayoutMyExamsExamIdRoute = LayoutMyExamsExamIdRouteImport.update({
  id: '/my/exams_/$examId',
  path: '/my/exams/$examId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExamsExamIdWorkbenchRoute =
  LayoutExamsExamIdWorkbenchRouteImport.update({
    id: '/workbench',
    path: '/workbench',
    getParentRoute: () => LayoutExamsExamIdRoute,
  } as any)
const LayoutExamsExamIdScoresRoute = LayoutExamsExamIdScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => LayoutExamsExamIdRoute,
} as any)
const LayoutExamsExamIdReportRoute = LayoutExamsExamIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => LayoutExamsExamIdRoute,
} as any)
const LayoutExamsExamIdQuestionsRoute =
  LayoutExamsExamIdQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => LayoutExamsExamIdRoute,
  } as any)
const LayoutExamsExamIdMarkingRoute =
  LayoutExamsExamIdMarkingRouteImport.update({
    id: '/marking',
    path: '/marking',
    getParentRoute: () => LayoutExamsExamIdRoute,
  } as any)
const LayoutExamsExamIdGradingRoute =
  LayoutExamsExamIdGradingRouteImport.update({
    id: '/grading',
    path: '/grading',
    getParentRoute: () => LayoutExamsExamIdRoute,
  } as any)
const LayoutExamsExamIdAnswersRoute =
  LayoutExamsExamIdAnswersRouteImport.update({
    id: '/answers',
    path: '/answers',
    getParentRoute: () => LayoutExamsExamIdRoute,
  } as any)
const LayoutExamsExamIdSubmissionsSubmissionIdReviewRoute =
  LayoutExamsExamIdSubmissionsSubmissionIdReviewRouteImport.update({
    id: '/submissions/$submissionId/review',
    path: '/submissions/$submissionId/review',
    getParentRoute: () => LayoutExamsExamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/classes': typeof LayoutClassesRoute
  '/compose': typeof LayoutComposeRoute
  '/exams': typeof LayoutExamsRoute
  '/getting-started': typeof LayoutGettingStartedRoute
  '/org-settings': typeof LayoutOrgSettingsRoute
  '/platform': typeof LayoutPlatformRoute
  '/settings': typeof LayoutSettingsRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/exams/$examId': typeof LayoutExamsExamIdRouteWithChildren
  '/my/exams': typeof LayoutMyExamsRoute
  '/platform/$orgId': typeof LayoutPlatformOrgIdRoute
  '/platform/commerce': typeof LayoutPlatformCommerceRoute
  '/platform/routing': typeof LayoutPlatformRoutingRoute
  '/platform/settings': typeof LayoutPlatformSettingsRoute
  '/platform/usage': typeof LayoutPlatformUsageRoute
  '/exams/$examId/answers': typeof LayoutExamsExamIdAnswersRoute
  '/exams/$examId/grading': typeof LayoutExamsExamIdGradingRoute
  '/exams/$examId/marking': typeof LayoutExamsExamIdMarkingRoute
  '/exams/$examId/questions': typeof LayoutExamsExamIdQuestionsRoute
  '/exams/$examId/report': typeof LayoutExamsExamIdReportRoute
  '/exams/$examId/scores': typeof LayoutExamsExamIdScoresRoute
  '/exams/$examId/workbench': typeof LayoutExamsExamIdWorkbenchRoute
  '/my/exams/$examId': typeof LayoutMyExamsExamIdRoute
  '/exams/$examId/': typeof LayoutExamsExamIdIndexRoute
  '/exams/$examId/submissions/$submissionId/review': typeof LayoutExamsExamIdSubmissionsSubmissionIdReviewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/classes': typeof LayoutClassesRoute
  '/compose': typeof LayoutComposeRoute
  '/exams': typeof LayoutExamsRoute
  '/getting-started': typeof LayoutGettingStartedRoute
  '/org-settings': typeof LayoutOrgSettingsRoute
  '/platform': typeof LayoutPlatformRoute
  '/settings': typeof LayoutSettingsRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/': typeof LayoutIndexRoute
  '/my/exams': typeof LayoutMyExamsRoute
  '/platform/$orgId': typeof LayoutPlatformOrgIdRoute
  '/platform/commerce': typeof LayoutPlatformCommerceRoute
  '/platform/routing': typeof LayoutPlatformRoutingRoute
  '/platform/settings': typeof LayoutPlatformSettingsRoute
  '/platform/usage': typeof LayoutPlatformUsageRoute
  '/exams/$examId/answers': typeof LayoutExamsExamIdAnswersRoute
  '/exams/$examId/grading': typeof LayoutExamsExamIdGradingRoute
  '/exams/$examId/marking': typeof LayoutExamsExamIdMarkingRoute
  '/exams/$examId/questions': typeof LayoutExamsExamIdQuestionsRoute
  '/exams/$examId/report': typeof LayoutExamsExamIdReportRoute
  '/exams/$examId/scores': typeof LayoutExamsExamIdScoresRoute
  '/exams/$examId/workbench': typeof LayoutExamsExamIdWorkbenchRoute
  '/my/exams/$examId': typeof LayoutMyExamsExamIdRoute
  '/exams/$examId': typeof LayoutExamsExamIdIndexRoute
  '/exams/$examId/submissions/$submissionId/review': typeof LayoutExamsExamIdSubmissionsSubmissionIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/classes': typeof LayoutClassesRoute
  '/_layout/compose': typeof LayoutComposeRoute
  '/_layout/exams': typeof LayoutExamsRoute
  '/_layout/getting-started': typeof LayoutGettingStartedRoute
  '/_layout/org-settings': typeof LayoutOrgSettingsRoute
  '/_layout/platform': typeof LayoutPlatformRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/signup_/verify': typeof SignupVerifyRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/exams_/$examId': typeof LayoutExamsExamIdRouteWithChildren
  '/_layout/my/exams': typeof LayoutMyExamsRoute
  '/_layout/platform_/$orgId': typeof LayoutPlatformOrgIdRoute
  '/_layout/platform_/commerce': typeof LayoutPlatformCommerceRoute
  '/_layout/platform_/routing': typeof LayoutPlatformRoutingRoute
  '/_layout/platform_/settings': typeof LayoutPlatformSettingsRoute
  '/_layout/platform_/usage': typeof LayoutPlatformUsageRoute
  '/_layout/exams_/$examId/answers': typeof LayoutExamsExamIdAnswersRoute
  '/_layout/exams_/$examId/grading': typeof LayoutExamsExamIdGradingRoute
  '/_layout/exams_/$examId/marking': typeof LayoutExamsExamIdMarkingRoute
  '/_layout/exams_/$examId/questions': typeof LayoutExamsExamIdQuestionsRoute
  '/_layout/exams_/$examId/report': typeof LayoutExamsExamIdReportRoute
  '/_layout/exams_/$examId/scores': typeof LayoutExamsExamIdScoresRoute
  '/_layout/exams_/$examId/workbench': typeof LayoutExamsExamIdWorkbenchRoute
  '/_layout/my/exams_/$examId': typeof LayoutMyExamsExamIdRoute
  '/_layout/exams_/$examId/': typeof LayoutExamsExamIdIndexRoute
  '/_layout/exams_/$examId/submissions/$submissionId/review': typeof LayoutExamsExamIdSubmissionsSubmissionIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/classes'
    | '/compose'
    | '/exams'
    | '/getting-started'
    | '/org-settings'
    | '/platform'
    | '/settings'
    | '/signup/verify'
    | '/exams/$examId'
    | '/my/exams'
    | '/platform/$orgId'
    | '/platform/commerce'
    | '/platform/routing'
    | '/platform/settings'
    | '/platform/usage'
    | '/exams/$examId/answers'
    | '/exams/$examId/grading'
    | '/exams/$examId/marking'
    | '/exams/$examId/questions'
    | '/exams/$examId/report'
    | '/exams/$examId/scores'
    | '/exams/$examId/workbench'
    | '/my/exams/$examId'
    | '/exams/$examId/'
    | '/exams/$examId/submissions/$submissionId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/classes'
    | '/compose'
    | '/exams'
    | '/getting-started'
    | '/org-settings'
    | '/platform'
    | '/settings'
    | '/signup/verify'
    | '/'
    | '/my/exams'
    | '/platform/$orgId'
    | '/platform/commerce'
    | '/platform/routing'
    | '/platform/settings'
    | '/platform/usage'
    | '/exams/$examId/answers'
    | '/exams/$examId/grading'
    | '/exams/$examId/marking'
    | '/exams/$examId/questions'
    | '/exams/$examId/report'
    | '/exams/$examId/scores'
    | '/exams/$examId/workbench'
    | '/my/exams/$examId'
    | '/exams/$examId'
    | '/exams/$examId/submissions/$submissionId/review'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/classes'
    | '/_layout/compose'
    | '/_layout/exams'
    | '/_layout/getting-started'
    | '/_layout/org-settings'
    | '/_layout/platform'
    | '/_layout/settings'
    | '/signup_/verify'
    | '/_layout/'
    | '/_layout/exams_/$examId'
    | '/_layout/my/exams'
    | '/_layout/platform_/$orgId'
    | '/_layout/platform_/commerce'
    | '/_layout/platform_/routing'
    | '/_layout/platform_/settings'
    | '/_layout/platform_/usage'
    | '/_layout/exams_/$examId/answers'
    | '/_layout/exams_/$examId/grading'
    | '/_layout/exams_/$examId/marking'
    | '/_layout/exams_/$examId/questions'
    | '/_layout/exams_/$examId/report'
    | '/_layout/exams_/$examId/scores'
    | '/_layout/exams_/$examId/workbench'
    | '/_layout/my/exams_/$examId'
    | '/_layout/exams_/$examId/'
    | '/_layout/exams_/$examId/submissions/$submissionId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SignupVerifyRoute: typeof SignupVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/signup_/verify': {
      id: '/signup_/verify'
      path: '/signup/verify'
      fullPath: '/signup/verify'
      preLoaderRoute: typeof SignupVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/platform': {
      id: '/_layout/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof LayoutPlatformRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/org-settings': {
      id: '/_layout/org-settings'
      path: '/org-settings'
      fullPath: '/org-settings'
      preLoaderRoute: typeof LayoutOrgSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/getting-started': {
      id: '/_layout/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof LayoutGettingStartedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/exams': {
      id: '/_layout/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof LayoutExamsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/compose': {
      id: '/_layout/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof LayoutComposeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/classes': {
      id: '/_layout/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof LayoutClassesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/platform_/usage': {
      id: '/_layout/platform_/usage'
      path: '/platform/usage'
      fullPath: '/platform/usage'
      preLoaderRoute: typeof LayoutPlatformUsageRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/platform_/settings': {
      id: '/_layout/platform_/settings'
      path: '/platform/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof LayoutPlatformSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/platform_/routing': {
      id: '/_layout/platform_/routing'
      path: '/platform/routing'
      fullPath: '/platform/routing'
      preLoaderRoute: typeof LayoutPlatformRoutingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/platform_/commerce': {
      id: '/_layout/platform_/commerce'
      path: '/platform/commerce'
      fullPath: '/platform/commerce'
      preLoaderRoute: typeof LayoutPlatformCommerceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/platform_/$orgId': {
      id: '/_layout/platform_/$orgId'
      path: '/platform/$orgId'
      fullPath: '/platform/$orgId'
      preLoaderRoute: typeof LayoutPlatformOrgIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my/exams': {
      id: '/_layout/my/exams'
      path: '/my/exams'
      fullPath: '/my/exams'
      preLoaderRoute: typeof LayoutMyExamsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/exams_/$examId': {
      id: '/_layout/exams_/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof LayoutExamsExamIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/exams_/$examId/': {
      id: '/_layout/exams_/$examId/'
      path: '/'
      fullPath: '/exams/$examId/'
      preLoaderRoute: typeof LayoutExamsExamIdIndexRouteImport
      parentRoute: typeof LayoutExamsExamIdRoute
    }
    '/_layout/my/exams_/$examId': {
      id: '/_layout/my/exams_/$examId'
      path: '/my/exams/$examId'
      fullPath: '/my/exams/$examId'
      preLoaderRoute: typeof LayoutMyExamsExamIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/exams_/$examId/workbench': {
      id: '/_layout/exams_/$examId/workbench'
      path: '/workbench'
      fullPath: '/exams/$examId/workbench'
      preLoaderRoute: typeof LayoutExamsExamIdWorkbenchRouteImport
      parentRoute: typeof LayoutExamsExamIdRoute
    }
    '/_layout/exams_/$examId/scores': {
      id: '/_layout/exams_/$examId/scores'
      path: '/scores'
      fullPath: '/exams/$examId/scores'
      preLoaderRoute: typeof LayoutExamsExamIdScoresRouteImport
      parentRoute: typeof LayoutExamsExamIdRoute
    }
    '/_layout/exams_/$examId/report': {
      id: '/_layout/exams_/$examId/report'
      path: '/report'
      fullPath: '/exams/$examId/report'
      preLoaderRoute: typeof LayoutExamsExamIdReportRouteImport
      parentRoute: typeof LayoutExamsExamIdRoute
    }
    '/_layout/exams_/$examId/questions': {
      id: '/_layout/exams_/$examId/questions'
      path: '/questions'
      fullPath: '/exams/$examId/questions'
      preLoaderRoute: typeof LayoutExamsExamIdQuestionsRouteImport
      parentRoute: typeof LayoutExamsExamIdRoute
    }
    '/_layout/exams_/$examId/marking': {
      id: '/_layout/exams_/$examId/marking'
      path: '/marking'
      fullPath: '/exams/$examId/marking'
      preLoaderRoute: typeof LayoutExamsExamIdMarkingRouteImport
      parentRoute: typeof LayoutExamsExamIdRoute
    }
    '/_layout/exams_/$examId/grading': {
      id: '/_layout/exams_/$examId/grading'
      path: '/grading'
      fullPath: '/exams/$examId/grading'
      preLoaderRoute: typeof LayoutExamsExamIdGradingRouteImport
      parentRoute: typeof LayoutExamsExamIdRoute
    }
    '/_layout/exams_/$examId/answers': {
      id: '/_layout/exams_/$examId/answers'
      path: '/answers'
      fullPath: '/exams/$examId/answers'
      preLoaderRoute: typeof LayoutExamsExamIdAnswersRouteImport
      parentRoute: typeof LayoutExamsExamIdRoute
    }
    '/_layout/exams_/$examId/submissions/$submissionId/review': {
      id: '/_layout/exams_/$examId/submissions/$submissionId/review'
      path: '/submissions/$submissionId/review'
      fullPath: '/exams/$examId/submissions/$submissionId/review'
      preLoaderRoute: typeof LayoutExamsExamIdSubmissionsSubmissionIdReviewRouteImport
      parentRoute: typeof LayoutExamsExamIdRoute
    }
  }
}

interface LayoutExamsExamIdRouteChildren {
  LayoutExamsExamIdAnswersRoute: typeof LayoutExamsExamIdAnswersRoute
  LayoutExamsExamIdGradingRoute: typeof LayoutExamsExamIdGradingRoute
  LayoutExamsExamIdMarkingRoute: typeof LayoutExamsExamIdMarkingRoute
  LayoutExamsExamIdQuestionsRoute: typeof LayoutExamsExamIdQuestionsRoute
  LayoutExamsExamIdReportRoute: typeof LayoutExamsExamIdReportRoute
  LayoutExamsExamIdScoresRoute: typeof LayoutExamsExamIdScoresRoute
  LayoutExamsExamIdWorkbenchRoute: typeof LayoutExamsExamIdWorkbenchRoute
  LayoutExamsExamIdIndexRoute: typeof LayoutExamsExamIdIndexRoute
  LayoutExamsExamIdSubmissionsSubmissionIdReviewRoute: typeof LayoutExamsExamIdSubmissionsSubmissionIdReviewRoute
}

const LayoutExamsExamIdRouteChildren: LayoutExamsExamIdRouteChildren = {
  LayoutExamsExamIdAnswersRoute: LayoutExamsExamIdAnswersRoute,
  LayoutExamsExamIdGradingRoute: LayoutExamsExamIdGradingRoute,
  LayoutExamsExamIdMarkingRoute: LayoutExamsExamIdMarkingRoute,
  LayoutExamsExamIdQuestionsRoute: LayoutExamsExamIdQuestionsRoute,
  LayoutExamsExamIdReportRoute: LayoutExamsExamIdReportRoute,
  LayoutExamsExamIdScoresRoute: LayoutExamsExamIdScoresRoute,
  LayoutExamsExamIdWorkbenchRoute: LayoutExamsExamIdWorkbenchRoute,
  LayoutExamsExamIdIndexRoute: LayoutExamsExamIdIndexRoute,
  LayoutExamsExamIdSubmissionsSubmissionIdReviewRoute:
    LayoutExamsExamIdSubmissionsSubmissionIdReviewRoute,
}

const LayoutExamsExamIdRouteWithChildren =
  LayoutExamsExamIdRoute._addFileChildren(LayoutExamsExamIdRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutClassesRoute: typeof LayoutClassesRoute
  LayoutComposeRoute: typeof LayoutComposeRoute
  LayoutExamsRoute: typeof LayoutExamsRoute
  LayoutGettingStartedRoute: typeof LayoutGettingStartedRoute
  LayoutOrgSettingsRoute: typeof LayoutOrgSettingsRoute
  LayoutPlatformRoute: typeof LayoutPlatformRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutExamsExamIdRoute: typeof LayoutExamsExamIdRouteWithChildren
  LayoutMyExamsRoute: typeof LayoutMyExamsRoute
  LayoutPlatformOrgIdRoute: typeof LayoutPlatformOrgIdRoute
  LayoutPlatformCommerceRoute: typeof LayoutPlatformCommerceRoute
  LayoutPlatformRoutingRoute: typeof LayoutPlatformRoutingRoute
  LayoutPlatformSettingsRoute: typeof LayoutPlatformSettingsRoute
  LayoutPlatformUsageRoute: typeof LayoutPlatformUsageRoute
  LayoutMyExamsExamIdRoute: typeof LayoutMyExamsExamIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutClassesRoute: LayoutClassesRoute,
  LayoutComposeRoute: LayoutComposeRoute,
  LayoutExamsRoute: LayoutExamsRoute,
  LayoutGettingStartedRoute: LayoutGettingStartedRoute,
  LayoutOrgSettingsRoute: LayoutOrgSettingsRoute,
  LayoutPlatformRoute: LayoutPlatformRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutExamsExamIdRoute: LayoutExamsExamIdRouteWithChildren,
  LayoutMyExamsRoute: LayoutMyExamsRoute,
  LayoutPlatformOrgIdRoute: LayoutPlatformOrgIdRoute,
  LayoutPlatformCommerceRoute: LayoutPlatformCommerceRoute,
  LayoutPlatformRoutingRoute: LayoutPlatformRoutingRoute,
  LayoutPlatformSettingsRoute: LayoutPlatformSettingsRoute,
  LayoutPlatformUsageRoute: LayoutPlatformUsageRoute,
  LayoutMyExamsExamIdRoute: LayoutMyExamsExamIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SignupVerifyRoute: SignupVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
