/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutExamsRouteImport } from './routes/_layout/exams'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutExamsExamIdRouteImport } from './routes/_layout/exams_.$examId'
import { Route as LayoutExamsExamIdScoresRouteImport } from './routes/_layout/exams_.$examId.scores'
import { Route as LayoutExamsExamIdQuestionsRouteImport } from './routes/_layout/exams_.$examId.questions'
import { Route as LayoutExamsExamIdMarkingRouteImport } from './routes/_layout/exams_.$examId.marking'
import { Route as LayoutExamsExamIdGradingRouteImport } from './routes/_layout/exams_.$examId.grading'
import { Route as LayoutExamsExamIdAnswersRouteImport } from './routes/_layout/exams_.$examId.answers'
import { Route as LayoutExamsExamIdSubmissionsSubmissionIdReviewRouteImport } from './routes/_layout/exams_.$examId.submissions.$submissionId.review'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExamsRoute = LayoutExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExamsExamIdRoute = LayoutExamsExamIdRouteImport.update({
  id: '/exams_/$examId',
  path: '/exams/$examId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExamsExamIdScoresRoute = LayoutExamsExamIdScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => LayoutExamsExamIdRoute,
} as any)
const LayoutExamsExamIdQuestionsRoute =
  LayoutExamsExamIdQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => LayoutExamsExamIdRoute,
  } as any)
const LayoutExamsExamIdMarkingRoute =
  LayoutExamsExamIdMarkingRouteImport.update({
    id: '/marking',
    path: '/marking',
    getParentRoute: () => LayoutExamsExamIdRoute,
  } as any)
const LayoutExamsExamIdGradingRoute =
  LayoutExamsExamIdGradingRouteImport.update({
    id: '/grading',
    path: '/grading',
    getParentRoute: () => LayoutExamsExamIdRoute,
  } as any)
const LayoutExamsExamIdAnswersRoute =
  LayoutExamsExamIdAnswersRouteImport.update({
    id: '/answers',
    path: '/answers',
    getParentRoute: () => LayoutExamsExamIdRoute,
  } as any)
const LayoutExamsExamIdSubmissionsSubmissionIdReviewRoute =
  LayoutExamsExamIdSubmissionsSubmissionIdReviewRouteImport.update({
    id: '/submissions/$submissionId/review',
    path: '/submissions/$submissionId/review',
    getParentRoute: () => LayoutExamsExamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/exams': typeof LayoutExamsRoute
  '/settings': typeof LayoutSettingsRoute
  '/exams/$examId': typeof LayoutExamsExamIdRouteWithChildren
  '/exams/$examId/answers': typeof LayoutExamsExamIdAnswersRoute
  '/exams/$examId/grading': typeof LayoutExamsExamIdGradingRoute
  '/exams/$examId/marking': typeof LayoutExamsExamIdMarkingRoute
  '/exams/$examId/questions': typeof LayoutExamsExamIdQuestionsRoute
  '/exams/$examId/scores': typeof LayoutExamsExamIdScoresRoute
  '/exams/$examId/submissions/$submissionId/review': typeof LayoutExamsExamIdSubmissionsSubmissionIdReviewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/exams': typeof LayoutExamsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/exams/$examId': typeof LayoutExamsExamIdRouteWithChildren
  '/exams/$examId/answers': typeof LayoutExamsExamIdAnswersRoute
  '/exams/$examId/grading': typeof LayoutExamsExamIdGradingRoute
  '/exams/$examId/marking': typeof LayoutExamsExamIdMarkingRoute
  '/exams/$examId/questions': typeof LayoutExamsExamIdQuestionsRoute
  '/exams/$examId/scores': typeof LayoutExamsExamIdScoresRoute
  '/exams/$examId/submissions/$submissionId/review': typeof LayoutExamsExamIdSubmissionsSubmissionIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/exams': typeof LayoutExamsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/exams_/$examId': typeof LayoutExamsExamIdRouteWithChildren
  '/_layout/exams_/$examId/answers': typeof LayoutExamsExamIdAnswersRoute
  '/_layout/exams_/$examId/grading': typeof LayoutExamsExamIdGradingRoute
  '/_layout/exams_/$examId/marking': typeof LayoutExamsExamIdMarkingRoute
  '/_layout/exams_/$examId/questions': typeof LayoutExamsExamIdQuestionsRoute
  '/_layout/exams_/$examId/scores': typeof LayoutExamsExamIdScoresRoute
  '/_layout/exams_/$examId/submissions/$submissionId/review': typeof LayoutExamsExamIdSubmissionsSubmissionIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/exams'
    | '/settings'
    | '/exams/$examId'
    | '/exams/$examId/answers'
    | '/exams/$examId/grading'
    | '/exams/$examId/marking'
    | '/exams/$examId/questions'
    | '/exams/$examId/scores'
    | '/exams/$examId/submissions/$submissionId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/exams'
    | '/settings'
    | '/'
    | '/exams/$examId'
    | '/exams/$examId/answers'
    | '/exams/$examId/grading'
    | '/exams/$examId/marking'
    | '/exams/$examId/questions'
    | '/exams/$examId/scores'
    | '/exams/$examId/submissions/$submissionId/review'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/exams'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/exams_/$examId'
    | '/_layout/exams_/$examId/answers'
    | '/_layout/exams_/$examId/grading'
    | '/_layout/exams_/$examId/marking'
    | '/_layout/exams_/$examId/questions'
    | '/_layout/exams_/$examId/scores'
    | '/_layout/exams_/$examId/submissions/$submissionId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/exams': {
      id: '/_layout/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof LayoutExamsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/exams_/$examId': {
      id: '/_layout/exams_/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof LayoutExamsExamIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/exams_/$examId/scores': {
      id: '/_layout/exams_/$examId/scores'
      path: '/scores'
      fullPath: '/exams/$examId/scores'
      preLoaderRoute: typeof LayoutExamsExamIdScoresRouteImport
      parentRoute: typeof LayoutExamsExamIdRoute
    }
    '/_layout/exams_/$examId/questions': {
      id: '/_layout/exams_/$examId/questions'
      path: '/questions'
      fullPath: '/exams/$examId/questions'
      preLoaderRoute: typeof LayoutExamsExamIdQuestionsRouteImport
      parentRoute: typeof LayoutExamsExamIdRoute
    }
    '/_layout/exams_/$examId/marking': {
      id: '/_layout/exams_/$examId/marking'
      path: '/marking'
      fullPath: '/exams/$examId/marking'
      preLoaderRoute: typeof LayoutExamsExamIdMarkingRouteImport
      parentRoute: typeof LayoutExamsExamIdRoute
    }
    '/_layout/exams_/$examId/grading': {
      id: '/_layout/exams_/$examId/grading'
      path: '/grading'
      fullPath: '/exams/$examId/grading'
      preLoaderRoute: typeof LayoutExamsExamIdGradingRouteImport
      parentRoute: typeof LayoutExamsExamIdRoute
    }
    '/_layout/exams_/$examId/answers': {
      id: '/_layout/exams_/$examId/answers'
      path: '/answers'
      fullPath: '/exams/$examId/answers'
      preLoaderRoute: typeof LayoutExamsExamIdAnswersRouteImport
      parentRoute: typeof LayoutExamsExamIdRoute
    }
    '/_layout/exams_/$examId/submissions/$submissionId/review': {
      id: '/_layout/exams_/$examId/submissions/$submissionId/review'
      path: '/submissions/$submissionId/review'
      fullPath: '/exams/$examId/submissions/$submissionId/review'
      preLoaderRoute: typeof LayoutExamsExamIdSubmissionsSubmissionIdReviewRouteImport
      parentRoute: typeof LayoutExamsExamIdRoute
    }
  }
}

interface LayoutExamsExamIdRouteChildren {
  LayoutExamsExamIdAnswersRoute: typeof LayoutExamsExamIdAnswersRoute
  LayoutExamsExamIdGradingRoute: typeof LayoutExamsExamIdGradingRoute
  LayoutExamsExamIdMarkingRoute: typeof LayoutExamsExamIdMarkingRoute
  LayoutExamsExamIdQuestionsRoute: typeof LayoutExamsExamIdQuestionsRoute
  LayoutExamsExamIdScoresRoute: typeof LayoutExamsExamIdScoresRoute
  LayoutExamsExamIdSubmissionsSubmissionIdReviewRoute: typeof LayoutExamsExamIdSubmissionsSubmissionIdReviewRoute
}

const LayoutExamsExamIdRouteChildren: LayoutExamsExamIdRouteChildren = {
  LayoutExamsExamIdAnswersRoute: LayoutExamsExamIdAnswersRoute,
  LayoutExamsExamIdGradingRoute: LayoutExamsExamIdGradingRoute,
  LayoutExamsExamIdMarkingRoute: LayoutExamsExamIdMarkingRoute,
  LayoutExamsExamIdQuestionsRoute: LayoutExamsExamIdQuestionsRoute,
  LayoutExamsExamIdScoresRoute: LayoutExamsExamIdScoresRoute,
  LayoutExamsExamIdSubmissionsSubmissionIdReviewRoute:
    LayoutExamsExamIdSubmissionsSubmissionIdReviewRoute,
}

const LayoutExamsExamIdRouteWithChildren =
  LayoutExamsExamIdRoute._addFileChildren(LayoutExamsExamIdRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutExamsRoute: typeof LayoutExamsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutExamsExamIdRoute: typeof LayoutExamsExamIdRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutExamsRoute: LayoutExamsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutExamsExamIdRoute: LayoutExamsExamIdRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
