FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
        libgomp1 \
        libglib2.0-0 \
        libgl1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./ocr-service/requirements.txt /app/requirements.txt

RUN python -m pip install --upgrade pip \
    && python -m pip install paddlepaddle-gpu==3.3.0 -i https://www.paddlepaddle.org.cn/packages/stable/cu130/ \
    && python -m pip install -r /app/requirements.txt

COPY ./ocr-service/app /app/app

EXPOSE 8010

CMD ["fastapi", "run", "--host", "0.0.0.0", "--port", "8010", "app/main.py"]
